[package]
name = "libvapor"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]
members = ["tools/accuracy"]
default-members = ["."]
resolver = "2"

[lib]
name = "vapor"

[features]
# Use software math implementations even when the target supports hardware math.
force-soft = []

[dependencies]
simd-macros = { git = "https://github.com/calebzulawski/simd-macros" }

[dev-dependencies]
libvapor-accuracy = { path = "tools/accuracy", default-features = false }
paste = "1"
proptest = { version = "1", default-features = false, features = ["std"] }
