/*
 * Derived from Arm optimized-routines math/aarch64/advsimd/sinf.c and cosf.c;
 * SLEEF src/libm/sleefsimdsp.c (xsinf/xcosf) and src/common/misc.h, with changes.
 * SPDX-License-Identifier: BSL-1.0 AND MIT
 */

/*
 * Copyright Naoki Shibata and contributors 2010 - 2025.
 * SPDX-License-Identifier: BSL-1.0 AND MIT
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/*
 * Copyright (c) 1999-2022, Arm Limited.
 * Copyright (c) 2019-2025, Arm Limited.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use core::simd::prelude::*;

// Reduction/sign handling: Arm optimized-routines advsimd/sinf.c and cosf.c.
// Polynomial and pi split: SLEEF sleefsimdsp.c (xsinf/xcosf) and misc.h.
#[inline]
pub(crate) fn sin_cos_f32<const N: usize, const COS: bool>(x: Simd<f32, N>) -> Simd<f32, N> {
    let ax = x.abs();
    let slow = ax.simd_ge(Simd::splat(125.0)) | !x.is_finite();
    let a = slow.select(Simd::splat(0.0), ax);
    let count = a * Simd::splat(core::f32::consts::FRAC_1_PI);
    let count = if COS { count + Simd::splat(0.5) } else { count };
    let shift = Simd::splat(12582912.0f32);
    let shifted = count + shift;
    let odd = shifted.to_bits() << 31;
    let n = shifted - shift;
    let n = if COS { n - Simd::splat(0.5) } else { n };
    let r = a - n * Simd::splat(3.1414794921875f32);
    let r = r - n * Simd::splat(0.00011315941810607910156f32);
    let r = r - n * Simd::splat(1.9841872589410058936e-09f32);
    let z = r * r;
    let p = Simd::splat(2.6083159809786593541503e-06f32) * z
        + Simd::splat(-0.0001981069071916863322258f32);
    let p = p * z + Simd::splat(0.00833307858556509017944336f32);
    let p = p * z + Simd::splat(-0.166666597127914428710938f32);
    let y = z * (p * r) + r;
    let sign = if COS {
        odd
    } else {
        odd ^ (x.to_bits() & Simd::splat(1 << 31))
    };
    let y = Simd::from_bits(y.to_bits() ^ sign);
    let tiny = ax.simd_lt(Simd::splat(1.0e-4));
    let y = tiny.select(if COS { Simd::splat(1.0) } else { x }, y);
    if !slow.any() {
        return y;
    }
    let (s, c) = super::sin_cos_non_fma::full_range_sincos_f32(slow.select(x, Simd::splat(0.0)));
    slow.select(if COS { c } else { s }, y)
}
