/*
 * Derived from Arm optimized-routines math/aarch64/advsimd/v_sincosf_common.h;
 * pi/2 split: SLEEF src/common/misc.h, with changes.
 */

/*
 * Copyright (c) 1999-2022, Arm Limited.
 * Copyright (c) 2023-2024, Arm Limited.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * Copyright Naoki Shibata and contributors 2010 - 2025.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use core::simd::prelude::*;

trait UnfusedMulAdd {
    fn mul_add(self, b: Self, c: Self) -> Self;
}

impl<const N: usize> UnfusedMulAdd for Simd<f32, N> {
    #[inline]
    fn mul_add(self, b: Self, c: Self) -> Self {
        self * b + c
    }
}

const SIN_F32: [f32; 3] = [
    f32::from_bits(0xbe2aaaa3), // -0x1.555546p-3
    f32::from_bits(0x3c0883b0), // 0x1.11076p-7
    f32::from_bits(0xb94ca75a), // -0x1.994eb4p-13
];

const COS_F32: [f32; 3] = [
    f32::from_bits(0x3d2aaaa5), // 0x1.55554ap-5
    f32::from_bits(0xbab6060d), // -0x1.6c0c1ap-10
    f32::from_bits(0x37ccf077), // 0x1.99e0eep-16
];

// Pi/2 split: SLEEF src/common/misc.h (pi chunks halved).
const PIO2_F32: [f32; 3] = [
    3.1414794921875f32 * 0.5,
    0.00011315941810607910156f32 * 0.5,
    1.9841872589410058936e-09f32 * 0.5,
];

#[inline]
fn sin_poly_f32<const N: usize>(z: Simd<f32, N>) -> Simd<f32, N> {
    let c = SIN_F32.map(Simd::splat);
    z.mul_add(z.mul_add(c[2], c[1]), c[0])
}

#[inline]
fn cos_poly_f32<const N: usize>(z: Simd<f32, N>) -> Simd<f32, N> {
    let c = COS_F32.map(Simd::splat);
    z.mul_add(z.mul_add(c[2], c[1]), c[0])
}

/// Computes both sine and cosine with a shared non-FMA range reduction.
#[inline]
pub(crate) fn sincos_f32<const N: usize>(x: Simd<f32, N>) -> (Simd<f32, N>, Simd<f32, N>) {
    let ax = x.abs();
    let slow = ax.simd_ge(Simd::splat(125.0f32)) | !x.is_finite();
    let a = slow.select(Simd::splat(0.0), ax);
    let shift = Simd::splat(12582912.0f32);
    let q = a.mul_add(Simd::splat(f32::from_bits(0x3f22f983)), shift);
    let n = q - shift;
    let quadrant = q.to_bits() & Simd::splat(3);
    let r = n.mul_add(Simd::splat(-PIO2_F32[0]), a);
    let r = n.mul_add(Simd::splat(-PIO2_F32[1]), r);
    let r = n.mul_add(Simd::splat(-PIO2_F32[2]), r);
    let r2 = r * r;
    let s = (r * r2).mul_add(sin_poly_f32(r2), r);
    let p = r2.mul_add(cos_poly_f32(r2), Simd::splat(-0.5));
    let c = r2.mul_add(p, Simd::splat(1.0));
    let swap = (quadrant & Simd::splat(1)).simd_ne(Simd::splat(0));
    let ss = swap.select(c, s);
    let cc = swap.select(s, c);
    let sin_sign = ((quadrant & Simd::splat(2)) << (31 - 1)) ^ (x.to_bits() & Simd::splat(1 << 31));
    let cos_sign = ((quadrant + Simd::splat(1)) & Simd::splat(2)) << (31 - 1);
    let ss = Simd::from_bits(ss.to_bits() ^ sin_sign);
    let cc = Simd::from_bits(cc.to_bits() ^ cos_sign);
    let tiny = ax.simd_lt(Simd::splat(1.0e-4f32));
    let ss = tiny.select(x, ss);
    let cc = tiny.select(Simd::splat(1.0), cc);
    if !slow.any() {
        return (ss, cc);
    }
    let (fs, fc) = super::sin_cos_non_fma::full_range_sincos_f32(slow.select(x, Simd::splat(0.0)));
    (slow.select(fs, ss), slow.select(fc, cc))
}
