/*
 * Derived from Arm optimized-routines math/aarch64/advsimd/expf.c and exp2f.c, with changes.
 * Polynomials: SLEEF src/libm/sleefsimdsp.c; ln(2) split: src/common/misc.h.
 * SPDX-License-Identifier: BSL-1.0 AND MIT
 */

/*
 * Copyright Naoki Shibata and contributors 2010 - 2025.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/*
 * Copyright (c) 1999-2022, Arm Limited.
 * Copyright (c) 2019-2026, Arm Limited.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use core::simd::prelude::*;

// Coefficients: SLEEF src/libm/sleefsimdsp.c (xexpf).
#[inline]
fn exp_poly_f32<const N: usize>(z: Simd<f32, N>) -> Simd<f32, N> {
    let c0 = Simd::splat(f32::from_bits(0x3f800000)); // 1
    let c1 = Simd::splat(f32::from_bits(0x3f800000)); // 1
    let c2 = Simd::splat(f32::from_bits(0x3f000000)); // 0.5
    let c3 = Simd::splat(f32::from_bits(0x3e2aaaab)); // 0.166666671633720397949219
    let c4 = Simd::splat(f32::from_bits(0x3d2aaa7a)); // 0.0416664853692054748535156
    let c5 = Simd::splat(f32::from_bits(0x3c0888a6)); // 0.00833336077630519866943359
    let c6 = Simd::splat(f32::from_bits(0x3ab696c9)); // 0.00139304355252534151077271
    let c7 = Simd::splat(f32::from_bits(0x39502bda)); // 0.000198527617612853646278381
    let p0_0 = c1 * z + c0;
    let p0_1 = c3 * z + c2;
    let p0_2 = c5 * z + c4;
    let p0_3 = c7 * z + c6;
    let z2 = z * z;
    let p1_0 = p0_1 * z2 + p0_0;
    let p1_1 = p0_3 * z2 + p0_2;
    let z4 = z2 * z2;
    let p2_0 = p1_1 * z4 + p1_0;
    p2_0
}

// Coefficients: SLEEF src/libm/sleefsimdsp.c (xexp2f_u35).
#[inline]
fn exp2_poly_f32<const N: usize>(z: Simd<f32, N>) -> Simd<f32, N> {
    let c0 = Simd::splat(f32::from_bits(0x3f800000)); // +0.1000000000e+1
    let c1 = Simd::splat(f32::from_bits(0x3f317218)); // +0.6931471825e+0
    let c2 = Simd::splat(f32::from_bits(0x3e75fdec)); // +0.2402264476e+0
    let c3 = Simd::splat(f32::from_bits(0x3d63579c)); // +0.5550347269e-1
    let c4 = Simd::splat(f32::from_bits(0x3c1d966e)); // +0.9618384764e-2
    let c5 = Simd::splat(f32::from_bits(0x3aaf8a33)); // +0.1339262701e-2
    let c6 = Simd::splat(f32::from_bits(0x39210d90)); // +0.1535920892e-3
    let p0_0 = c1 * z + c0;
    let p0_1 = c3 * z + c2;
    let p0_2 = c5 * z + c4;
    let z2 = z * z;
    let p1_0 = p0_1 * z2 + p0_0;
    let p1_1 = c6 * z2 + p0_2;
    let z4 = z2 * z2;
    let p2_0 = p1_1 * z4 + p1_0;
    p2_0
}

// Reduction/scaling: Arm optimized-routines advsimd/expf.c and exp2f.c. ln(2) split: SLEEF misc.h.
#[inline]
fn kernel_f32<const N: usize, const BASE2: bool>(x: Simd<f32, N>) -> Simd<f32, N> {
    let limit = if BASE2 { 120.0 } else { 85.0 };
    if !x.abs().simd_lt(Simd::splat(limit)).all() {
        return special_f32::<N, BASE2>(x);
    }
    let a = x;
    let z = if BASE2 {
        a
    } else {
        a * Simd::splat(1.4426950408889634074f32)
    };
    let shift = Simd::splat(12582912.0f32);
    let shifted = z + shift;
    let n = shifted - shift;
    let r = if BASE2 {
        a - n
    } else {
        (a - n * Simd::splat(0.693145751953125f32)) - n * Simd::splat(1.428606765330187045e-06f32)
    };
    let poly = if BASE2 {
        exp2_poly_f32(r)
    } else {
        exp_poly_f32(r)
    };
    let scale = Simd::<f32, N>::from_bits((shifted.to_bits() << 23) + Simd::splat(0x3f800000));
    let y = poly * scale;
    y
}

/// Computes e^x with a table-free non-FMA polynomial.
#[inline]
pub fn exp_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    kernel_f32::<N, false>(x)
}

/// Computes 2^x with a table-free non-FMA polynomial.
#[inline]
pub fn exp2_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    kernel_f32::<N, true>(x)
}

#[cold]
#[inline(never)]
fn special_f32<const N: usize, const BASE2: bool>(x: Simd<f32, N>) -> Simd<f32, N> {
    let limit = if BASE2 { 120.0 } else { 85.0 };
    let slow = !x.abs().simd_lt(Simd::splat(limit));
    let a = slow.select(Simd::splat(0.0), x);
    let y = kernel_f32::<N, BASE2>(a);
    let a = slow.select(x, Simd::splat(0.0));
    let fallback = if BASE2 {
        super::super::full_range::exp2_f32(a)
    } else {
        super::super::full_range::exp_f32(a)
    };
    slow.select(fallback, y)
}
