/*
 * Derived from Arm optimized-routines math/aarch64/advsimd/exp.c and exp2.c, with changes.
 * Polynomials: SLEEF src/libm/sleefsimddp.c.
 * Table and ln(2) split: musl exp2f_data.c and exp_data.c.
 * SPDX-License-Identifier: BSL-1.0 AND MIT
 */

/*
 * Copyright Naoki Shibata and contributors 2010 - 2025.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/*
 * Copyright (c) 1999-2022, Arm Limited.
 * Copyright (c) 2019-2025, Arm Limited.
 * Copyright (c) 2017-2018, Arm Limited.
 * Copyright (c) 2018, Arm Limited.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use core::simd::prelude::*;

// Coefficients: SLEEF src/libm/sleefsimddp.c (xexp) (truncated).
#[inline]
fn exp_poly_f64<const N: usize>(z: Simd<f64, N>) -> Simd<f64, N> {
    let c0 = Simd::splat(f64::from_bits(0x3ff0000000000000));
    let c1 = Simd::splat(f64::from_bits(0x3ff0000000000000));
    let c2 = Simd::splat(f64::from_bits(0x3fe0000000000000));
    let c3 = Simd::splat(f64::from_bits(0x3fc555555555555c));
    let c4 = Simd::splat(f64::from_bits(0x3fa555555555553e));
    let c5 = Simd::splat(f64::from_bits(0x3f8111111110eb39));
    let c6 = Simd::splat(f64::from_bits(0x3f56c16c16c20ba0));
    let z2 = z * z;
    let z4 = z2 * z2;
    let p01 = c1 * z + c0;
    let p23 = c3 * z + c2;
    let p45 = c5 * z + c4;
    (c6 * z2 + p45) * z4 + (p23 * z2 + p01)
}

// Coefficients: SLEEF src/libm/sleefsimddp.c (xexp2_u35) (truncated).
#[inline]
fn exp2_poly_f64<const N: usize>(z: Simd<f64, N>) -> Simd<f64, N> {
    let c0 = Simd::splat(f64::from_bits(0x3ff0000000000000));
    let c1 = Simd::splat(f64::from_bits(0x3fe62e42fefa39ef));
    let c2 = Simd::splat(f64::from_bits(0x3fcebfbdff82c5a1));
    let c3 = Simd::splat(f64::from_bits(0x3fac6b08d704a01f));
    let c4 = Simd::splat(f64::from_bits(0x3f83b2ab6fba08f0));
    let c5 = Simd::splat(f64::from_bits(0x3f55d87fe78c5960));
    let c6 = Simd::splat(f64::from_bits(0x3f24309130cb34ec));
    let z2 = z * z;
    let z4 = z2 * z2;
    let p01 = c1 * z + c0;
    let p23 = c3 * z + c2;
    let p45 = c5 * z + c4;
    (c6 * z2 + p45) * z4 + (p23 * z2 + p01)
}

// Reduction/scaling: Arm optimized-routines advsimd/exp.c and exp2.c.
// Table: musl exp2f_data.c. ln(2) split: musl exp_data.c.
#[inline]
fn kernel_f64<const N: usize, const BASE2: bool>(x: Simd<f64, N>) -> Simd<f64, N> {
    let limit = if BASE2 { 1000.0 } else { 700.0 };
    if !x.abs().simd_lt(Simd::splat(limit)).all() {
        return special_f64::<N, BASE2>(x);
    }
    let a = x;
    let z = if BASE2 {
        a
    } else {
        a * Simd::splat(1.4426950408889634074f64)
    };
    let shift = Simd::splat(211106232532992.0f64);
    let shifted = z + shift;
    let n = shifted - shift;
    let r = if BASE2 {
        a - n
    } else {
        (a + n * Simd::splat(super::super::data::NEG_LN2_HI_F64 * 128.0))
            + n * Simd::splat(super::super::data::NEG_LN2_LO_F64 * 128.0)
    };
    let poly = if BASE2 {
        exp2_poly_f64(r)
    } else {
        exp_poly_f64(r)
    };
    let bits = shifted.to_bits();
    let index = (bits & Simd::splat(31)).cast::<usize>();
    // Scale table: musl exp2f_data.c.
    let table = Simd::gather_or(&super::super::data::TABLE_F32, index, Simd::splat(0));
    let scale = Simd::<f64, N>::from_bits(table + (bits << 47));
    let y = poly * scale;
    y
}

/// Computes e^x with non-FMA reduction and a 32-entry scale table.
#[inline]
pub fn exp_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    kernel_f64::<N, false>(x)
}

/// Computes 2^x with non-FMA reduction and a 32-entry scale table.
#[inline]
pub fn exp2_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    kernel_f64::<N, true>(x)
}

#[cold]
#[inline(never)]
fn special_f64<const N: usize, const BASE2: bool>(x: Simd<f64, N>) -> Simd<f64, N> {
    let limit = if BASE2 { 1000.0 } else { 700.0 };
    let slow = !x.abs().simd_lt(Simd::splat(limit));
    let a = slow.select(Simd::splat(0.0), x);
    let y = kernel_f64::<N, BASE2>(a);
    let a = slow.select(x, Simd::splat(0.0));
    let fallback = if BASE2 {
        super::super::full_range::exp2_f64(a)
    } else {
        super::super::full_range::exp_f64(a)
    };
    slow.select(fallback, y)
}
