// Gamma polynomials derived from SLEEF src/libm/sleefsimddp.c (gammak).
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: MIT AND BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

pub const COEFFICIENTS: [[f64; 3]; 23] = [
    [
        -156.801412704022726379848862,
        0.2947916772827614196e+2,
        0.7074816000864609279e-7,
    ],
    [
        1.120804464289911606838558160000,
        0.1281459691827820109e+3,
        0.4009244333008730443e-6,
    ],
    [
        13.39798545514258921833306020000,
        0.2617544025784515043e+3,
        0.1040114641628246946e-5,
    ],
    [
        -0.116546276599463200848033357000,
        0.3287022855685790432e+3,
        0.1508349150733329167e-5,
    ],
    [
        -1.391801093265337481495562410000,
        0.2818145867730348186e+3,
        0.1288143074933901020e-5,
    ],
    [
        0.015056113040026424412918973400,
        0.1728670414673559605e+3,
        0.4744167749884993937e-6,
    ],
    [
        0.179540117061234856098844714000,
        0.7748735764030416817e+2,
        -0.6554816306542489902e-7,
    ],
    [
        -0.002481743600264997730942489280,
        0.2512856643080930752e+2,
        -0.3189252471452599844e-6,
    ],
    [
        -0.029527880945699120504851034100,
        0.5766792106140076868e+1,
        0.1358883821470355377e-6,
    ],
    [
        0.000540164767892604515196325186,
        0.7270275473996180571e+0,
        -0.4343931277157336040e-6,
    ],
    [
        0.006403362833808069794787256200,
        0.8396709124579147809e-1,
        0.9724785897406779555e-6,
    ],
    [
        -0.000162516262783915816896611252,
        -0.8211558669746804595e-1,
        -0.2036886057225966011e-5,
    ],
    [
        -0.001914438498565477526465972390,
        0.6828831828341884458e-1,
        0.4373363141819725815e-5,
    ],
    [
        7.20489541602001055898311517e-05,
        -0.7712481339961671511e-1,
        -0.9439951268304008677e-5,
    ],
    [
        0.000839498720672087279971000786,
        0.8337492023017314957e-1,
        0.2050727030376389804e-4,
    ],
    [
        -5.17179090826059219329394422e-05,
        -0.9094964931456242518e-1,
        -0.4492620183431184018e-4,
    ],
    [
        -0.000592166437353693882857342347,
        0.1000996313575929358e+0,
        0.9945751236071875931e-4,
    ],
    [
        6.97281375836585777403743539e-05,
        -0.1113342861544207724e+0,
        -0.2231547599034983196e-3,
    ],
    [
        0.000784039221720066627493314301,
        0.1255096673213020875e+0,
        0.5096695247101967622e-3,
    ],
    [
        -0.000229472093621399176949318732,
        -0.1440498967843054368e+0,
        -0.1192753911667886971e-2,
    ],
    [
        -0.002681327160493827160473958490,
        0.1695571770041949811e+0,
        0.2890510330742210310e-2,
    ],
    [
        0.003472222222222222222175164840,
        -0.2073855510284092762e+0,
        -0.7385551028674461858e-2,
    ],
    [
        0.083333333333333333335592087900,
        0.2705808084277815939e+0,
        0.2058080842778455335e-1,
    ],
];
