//! Integer powers, roots, and compounding with small-exponent fast paths.
// Derived from SLEEF src/libm/sleefsimddp.c and src/common/dd.h, with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: MIT AND BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use crate::precision::{exp_value, log1p_dd, log_float_dd, madd, Dd};
use core::simd::prelude::*;

// Binary exponentiation is a project extension of the SLEEF-derived kernels.
// Restrict this path to |n| <= 32 and 2^-16 <= base <= 2^16: every
// intermediate and its reciprocal stays normal, with room for compensation.
#[inline]
fn small_power_domain<const N: usize>(base: Simd<f64, N>, n: Simd<i64, N>) -> bool {
    (base.simd_ge(Simd::splat(1.0 / 65536.0))
        & base.simd_le(Simd::splat(65536.0))
        & n.simd_ge(Simd::splat(-32))
        & n.simd_le(Simd::splat(32)))
    .all()
}

#[inline]
fn small_power_dd<const N: usize>(mut base: Dd<N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let negative = n.simd_lt(Simd::splat(0));
    let bits = negative.select(-n, n).cast::<u32>();
    let mut result = Dd::select(
        (bits & Simd::splat(1)).simd_ne(Simd::splat(0)).cast(),
        base,
        Dd::splat(1.0, 0.0),
    );
    for bit in [2, 4, 8, 16, 32] {
        if bits.simd_lt(Simd::splat(bit)).all() {
            break;
        }
        base = base.square().normalize();
        result = Dd::select(
            (bits & Simd::splat(bit)).simd_ne(Simd::splat(0)).cast(),
            result.mul(base).normalize(),
            result,
        );
    }
    let q = Simd::splat(1.0) / result.hi;
    let residual = if crate::backend::use_hardware_fma_f64::<N>() {
        madd(-q, result.hi, Simd::splat(1.0))
    } else {
        let product = Dd::product(q, result.hi);
        (Simd::splat(1.0) - product.hi) - product.lo
    };
    // SLEEF's reciprocal correction replaces the second division by q.
    // Its extra error is quadratic in the reciprocal's rounding error;
    // the domain guard keeps the selected powers and reciprocals normal.
    let reciprocal = madd(q, madd(-q, result.lo, residual), q);
    negative.select(reciprocal, result.value())
}

// At most 32 ordinary double-precision multiplications leave a generous
// margin before rounding to f32; no compensated products are needed here.
#[inline]
fn small_power_f32<const N: usize>(mut base: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let negative = n.simd_lt(Simd::splat(0));
    let bits = negative.select(-n, n).cast::<u32>();
    let mut result = (bits & Simd::splat(1))
        .simd_ne(Simd::splat(0))
        .cast::<i64>()
        .select(base, Simd::splat(1.0));
    for bit in [2, 4, 8, 16, 32] {
        if bits.simd_lt(Simd::splat(bit)).all() {
            break;
        }
        base *= base;
        result = (bits & Simd::splat(bit))
            .simd_ne(Simd::splat(0))
            .cast::<i64>()
            .select(result * base, result);
    }
    negative.select(Simd::splat(1.0) / result, result)
}

#[inline]
fn power_sign<const N: usize>(
    x: Simd<f64, N>,
    n: Simd<i64, N>,
    magnitude: Simd<f64, N>,
) -> Simd<f64, N> {
    let negative = x.is_sign_negative() & (n & Simd::splat(1)).simd_ne(Simd::splat(0));
    negative.select(-magnitude, magnitude)
}

// Splitting at 32 bits preserves every i64 exponent, including i64::MIN.
// A float conversion alone loses both the low bits and odd/even parity.
#[inline]
fn integer_dd<const N: usize>(n: Simd<i64, N>) -> Dd<N> {
    let hi = (n >> 32).cast::<i32>().cast::<f64>() * Simd::splat(4294967296.0);
    let lo = n.cast::<u64>().cast::<u32>().cast::<f64>();
    Dd::from(hi).add_float(lo).normalize()
}

/// Computes x raised to the signed 64-bit integer n for each lane.
/// Negative bases and signed zeros retain their sign for odd n; n=0 returns 1.
#[inline]
pub fn pown_f64<const N: usize>(x: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    if small_power_domain(x.abs(), n) {
        return power_sign(x, n, small_power_dd(Dd::from(x.abs()), n));
    }
    pown_large_f64(x, n)
}

#[inline(never)]
fn pown_large_f64<const N: usize>(x: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let regular = ax.is_finite() & ax.simd_ne(Simd::splat(0.0));
    let a = regular.select(ax, Simd::splat(1.0));
    let d = log_float_dd(a).mul(integer_dd(n)).normalize();
    let magnitude = exp_value(d);
    finish_pown(x, n, magnitude)
}

#[inline]
fn finish_pown<const N: usize>(
    x: Simd<f64, N>,
    n: Simd<i64, N>,
    magnitude: Simd<f64, N>,
) -> Simd<f64, N> {
    let ax = x.abs();
    let regular = ax.is_finite() & ax.simd_ne(Simd::splat(0.0));
    let negative = x.is_sign_negative() & (n & Simd::splat(1)).simd_ne(Simd::splat(0));
    let exceptional = (ax.simd_eq(Simd::splat(0.0)) ^ n.simd_lt(Simd::splat(0)))
        .select(Simd::splat(0.0), Simd::splat(f64::INFINITY));
    let magnitude = regular.select(magnitude, exceptional);
    let result = negative.select(-magnitude, magnitude);
    let result = x.is_nan().select(x + x, result);
    let result = n.simd_eq(Simd::splat(1)).select(x, result);
    let result = n
        .simd_eq(Simd::splat(-1))
        .select(Simd::splat(1.0) / x, result);
    n.simd_eq(Simd::splat(0)).select(Simd::splat(1.0), result)
}

/// Computes x raised to the signed 64-bit integer n for each lane.
/// Negative bases and signed zeros retain their sign for odd n; n=0 returns 1.
#[inline]
pub fn pown_f32<const N: usize>(x: Simd<f32, N>, n: Simd<i64, N>) -> Simd<f32, N> {
    let a = x.abs().cast::<f64>();
    if small_power_domain(a, n) {
        let magnitude = small_power_f32(a, n).cast::<f32>();
        let negative =
            x.is_sign_negative() & (n & Simd::splat(1)).simd_ne(Simd::splat(0)).cast::<i32>();
        return negative.select(-magnitude, magnitude);
    }
    pown_large_f32(x.cast(), n).cast()
}

// A double-precision log/exp is sufficient for a single-precision result.
// Converting n directly to f64 avoids the coarse f32 exponent rounding;
// odd/even parity still comes from the original integer in finish_pown.
#[inline(never)]
fn pown_large_f32<const N: usize>(x: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let regular = ax.is_finite() & ax.simd_ne(Simd::splat(0.0));
    let a = regular.select(ax, Simd::splat(1.0));
    finish_pown(x, n, crate::exp_f64(crate::log_f64(a) * n.cast::<f64>()))
}

/// Computes the principal nth root for each lane, using a signed 64-bit n.
/// Negative n gives the reciprocal root. Zero n and negative x with even n give NaN.
#[inline]
pub fn rootn_f64<const N: usize>(x: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let regular = ax.is_finite() & ax.simd_ne(Simd::splat(0.0));
    let a = regular.select(ax, Simd::splat(1.0));
    let exponent = n.simd_eq(Simd::splat(0)).select(Simd::splat(1), n);
    let d = log_float_dd(a).div(integer_dd(exponent)).normalize();
    let magnitude = exp_value(d);
    finish_rootn(x, n, magnitude)
}

#[inline]
fn finish_rootn<const N: usize>(
    x: Simd<f64, N>,
    n: Simd<i64, N>,
    magnitude: Simd<f64, N>,
) -> Simd<f64, N> {
    let result = if (x.simd_gt(Simd::splat(0.0)) & x.is_finite()).all() {
        magnitude
    } else {
        let ax = x.abs();
        let regular = ax.is_finite() & ax.simd_ne(Simd::splat(0.0));
        let odd = (n & Simd::splat(1)).simd_ne(Simd::splat(0));
        let exceptional = (ax.simd_eq(Simd::splat(0.0)) ^ n.simd_lt(Simd::splat(0)))
            .select(Simd::splat(0.0), Simd::splat(f64::INFINITY));
        let magnitude = regular.select(magnitude, exceptional);
        let negative = x.is_sign_negative() & odd;
        let result = negative.select(-magnitude, magnitude);
        let result = x.is_nan().select(x + x, result);
        (x.simd_lt(Simd::splat(0.0)) & !odd).select(Simd::splat(f64::NAN), result)
    };
    let result = n.simd_eq(Simd::splat(1)).select(x, result);
    let result = n
        .simd_eq(Simd::splat(-1))
        .select(Simd::splat(1.0) / x, result);
    n.simd_eq(Simd::splat(0))
        .select(Simd::splat(f64::NAN), result)
}

/// Computes the principal nth root for each lane, using a signed 64-bit n.
/// Negative n gives the reciprocal root. Zero n and negative x with even n give NaN.
#[inline]
pub fn rootn_f32<const N: usize>(x: Simd<f32, N>, n: Simd<i64, N>) -> Simd<f32, N> {
    let x = x.cast::<f64>();
    let ax = x.abs();
    let regular = ax.is_finite() & ax.simd_ne(Simd::splat(0.0));
    let a = regular.select(ax, Simd::splat(1.0));
    let exponent = n.simd_eq(Simd::splat(0)).select(Simd::splat(1), n);
    finish_rootn(
        x,
        n,
        crate::exp_f64(crate::log_f64(a) / exponent.cast::<f64>()),
    )
    .cast()
}

/// Computes (1+x) raised to the signed 64-bit integer n for each lane.
/// Retains small x even when 1+x rounds to 1. Inputs below -1 give NaN.
#[inline]
pub fn compoundn_f64<const N: usize>(x: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let base = Dd::from(x).add_float(Simd::splat(1.0)).normalize();
    if small_power_domain(base.hi, n) {
        return small_power_dd(base, n);
    }
    compoundn_large_f64(x, n)
}

#[inline(never)]
fn compoundn_large_f64<const N: usize>(x: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let regular = x.is_finite() & x.simd_gt(Simd::splat(-1.0));
    let a = regular.select(x, Simd::splat(0.0));
    let d = log1p_dd(a).mul(integer_dd(n)).normalize();
    finish_compoundn(x, n, exp_value(d))
}

#[inline]
fn finish_compoundn<const N: usize>(
    x: Simd<f64, N>,
    n: Simd<i64, N>,
    result: Simd<f64, N>,
) -> Simd<f64, N> {
    let regular = x.is_finite() & x.simd_gt(Simd::splat(-1.0));
    let exceptional = (x.simd_eq(Simd::splat(-1.0)) ^ n.simd_lt(Simd::splat(0)))
        .select(Simd::splat(0.0), Simd::splat(f64::INFINITY));
    let result = regular.select(result, exceptional);
    let result = x.is_nan().select(x + x, result);
    let result = n
        .simd_eq(Simd::splat(1))
        .select(Simd::splat(1.0) + x, result);
    let result = n.simd_eq(Simd::splat(0)).select(Simd::splat(1.0), result);
    x.simd_lt(Simd::splat(-1.0))
        .select(Simd::splat(f64::NAN), result)
}

/// Computes (1+x) raised to the signed 64-bit integer n for each lane.
/// Retains small x even when 1+x rounds to 1. Inputs below -1 give NaN.
#[inline]
pub fn compoundn_f32<const N: usize>(x: Simd<f32, N>, n: Simd<i64, N>) -> Simd<f32, N> {
    let x = x.cast::<f64>();
    let base = x + Simd::splat(1.0);
    if small_power_domain(base, n) {
        return small_power_f32(base, n).cast();
    }
    compoundn_large_f32(x, n).cast()
}

#[inline(never)]
fn compoundn_large_f32<const N: usize>(x: Simd<f64, N>, n: Simd<i64, N>) -> Simd<f64, N> {
    let regular = x.is_finite() & x.simd_gt(Simd::splat(-1.0));
    let a = regular.select(x, Simd::splat(0.0));
    finish_compoundn(x, n, crate::exp_f64(crate::log1p_f64(a) * n.cast::<f64>()))
}
