//! Cube root by exponent decomposition and reciprocal-root refinement.
// Derived from SLEEF src/libm/sleefsimddp.c and sleefsimdsp.c (xcbrt), with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: MIT AND BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use crate::precision::{frexp, madd, madd_f32, polynomial};
use core::simd::prelude::*;

/// Computes the real cube root for each lane, including negative inputs.
#[inline]
pub fn cbrt_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let regular = x.is_finite() & x.simd_ne(Simd::splat(0.0));
    let (m, e) = frexp(regular.select(x.abs(), Simd::splat(1.0)));
    let e = e.cast::<i32>();
    let q = (e + Simd::splat(6144)) / Simd::splat(3);
    let rem = e + Simd::splat(6144) - q * Simd::splat(3);
    let factor = rem.simd_eq(Simd::splat(1)).select(
        Simd::splat(1.2599210498948732),
        rem.simd_eq(Simd::splat(2))
            .select(Simd::splat(1.5874010519681994), Simd::splat(1.0)),
    );
    let mut r = polynomial(
        m,
        &[
            -0.640245898480692909870982,
            2.96155103020039511818595,
            -5.73353060922947843636166,
            6.03990368989458747961407,
            -3.85841935510444988821632,
            2.2307275302496609725722,
        ],
    );
    let r2 = r * r;
    r = r - (m * r2 * r2 - r) * Simd::splat(1.0 / 3.0);
    let y = m * r * r;
    let y = y - (Simd::splat(2.0 / 3.0) * y) * madd(y, r, Simd::splat(-1.0));
    // A cube root's exponent is always in the normal factor range.
    let power =
        Simd::<f64, N>::from_bits((q - Simd::splat(2048) + Simd::splat(1023)).cast::<u64>() << 52);
    let y = ((y * factor) * power).copysign(x);
    regular.select(y, x)
}

/// Computes the real cube root for each lane, including negative inputs.
#[inline]
pub fn cbrt_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let regular = x.is_finite() & x.simd_ne(Simd::splat(0.0));
    let a = regular.select(x.abs(), Simd::splat(1.0));
    let subnormal = a.simd_lt(Simd::splat(f32::MIN_POSITIVE));
    let a = subnormal.select(a * Simd::splat(33554432.0), a);
    let bits = a.to_bits();
    let e = (bits >> 23).cast::<i32>()
        - Simd::splat(126)
        - subnormal.select(Simd::splat(25), Simd::splat(0));
    let m = Simd::<f32, N>::from_bits((bits & Simd::splat(0x007fffff)) | Simd::splat(0x3f000000));
    let q = (e + Simd::splat(6144)) / Simd::splat(3);
    let rem = e + Simd::splat(6144) - q * Simd::splat(3);
    let factor = rem.simd_eq(Simd::splat(1)).select(
        Simd::splat(1.2599210498948732),
        rem.simd_eq(Simd::splat(2))
            .select(Simd::splat(1.5874010519681994), Simd::splat(1.0)),
    );
    let factor = factor
        * Simd::<f32, N>::from_bits((q - Simd::splat(2048) + Simd::splat(127)).cast::<u32>() << 23);
    let mut r = Simd::splat(-0.601564466953277587890625);
    for c in [
        2.8208892345428466796875,
        -5.532182216644287109375,
        5.898262500762939453125,
        -3.8095417022705078125,
        2.2241256237030029296875,
    ] {
        r = madd_f32(r, m, Simd::splat(c));
    }
    let y = m * r * r;
    let y = (y - (Simd::splat(2.0 / 3.0) * y) * madd_f32(y, r, Simd::splat(-1.0))) * factor;
    regular.select(y.copysign(x), x)
}
