//! Exponential minus one, with accurate reconstruction near zero.
// Derived from SLEEF src/libm/sleefsimddp.c and sleefsimdsp.c (expm1k), with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: MIT AND BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use crate::precision::{madd, madd_f32, polynomial, scale, scale_f32};
use core::simd::prelude::*;

const COEFFICIENTS: [f64; 10] = [
    2.08860621107283687536341e-09,
    2.51112930892876518610661e-08,
    2.75573911234900471893338e-07,
    2.75572362911928827629423e-06,
    2.4801587159235472998791e-05,
    0.000198412698960509205564975,
    0.00138888888889774492207962,
    0.00833333333331652721664984,
    0.0416666666666665047591422,
    0.166666666666666851703837,
];

/// Computes exp(x)-1 for each lane, preserving accuracy for small x.
#[inline]
pub fn expm1_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let regular = x.simd_ge(Simd::splat(-37.5)) & x.simd_le(Simd::splat(709.782712893384));
    let a = regular.select(x, Simd::splat(0.0));
    // Round to nearest using the current arithmetic contract; no libm call.
    let shift = Simd::splat(6755399441055744.0).copysign(a);
    let q = (a * Simd::splat(core::f64::consts::LOG2_E) + shift) - shift;
    let r = madd(
        q,
        Simd::splat(-0.69314718055966295651160180568695068359375),
        a,
    );
    let r = madd(
        q,
        Simd::splat(-2.82352905630315771225884481750134360255e-13),
        r,
    );
    let r2 = r * r;
    let u = r + madd(
        r2,
        Simd::splat(0.5),
        (r2 * r) * polynomial(r, &COEFFICIENTS),
    );
    let ret = q.simd_eq(Simd::splat(0.0)).select(
        u,
        scale(Simd::splat(1.0) + u, q.cast::<i64>()) - Simd::splat(1.0),
    );
    let ret = x.abs().simd_lt(Simd::splat(1.0e-16)).select(x, ret);
    let exceptional = x
        .simd_lt(Simd::splat(0.0))
        .select(Simd::splat(-1.0), Simd::splat(f64::INFINITY));
    let exceptional = x.is_nan().select(x + x, exceptional);
    regular.select(ret, exceptional)
}

/// Computes exp(x)-1 for each lane, preserving accuracy for small x.
#[inline]
pub fn expm1_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let regular = x.simd_ge(Simd::splat(-18.0)) & x.simd_le(Simd::splat(88.72283));
    let a = regular.select(x, Simd::splat(0.0));
    let shift = Simd::splat(12582912.0).copysign(a);
    let q = (a * Simd::splat(core::f32::consts::LOG2_E) + shift) - shift;
    let r = madd_f32(q, Simd::splat(-0.693145751953125), a);
    let r = madd_f32(q, Simd::splat(-1.428606765330187045e-6), r);
    let mut p = Simd::splat(0.000198527617612853646278381);
    for c in [
        0.00139304355252534151077271,
        0.00833336077630519866943359,
        0.0416664853692054748535156,
        0.166666671633720397949219,
        0.5,
    ] {
        p = madd_f32(p, r, Simd::splat(c));
    }
    let u = madd_f32(r * r, p, r);
    let value = q.simd_eq(Simd::splat(0.0)).select(
        u,
        scale_f32(Simd::splat(1.0) + u, q.cast()) - Simd::splat(1.0),
    );
    let value = x.abs().simd_lt(Simd::splat(1.0e-7)).select(x, value);
    let exceptional = x
        .simd_lt(Simd::splat(0.0))
        .select(Simd::splat(-1.0), Simd::splat(f32::INFINITY));
    regular.select(value, x.is_nan().select(x + x, exceptional))
}
