//! Gamma and logarithm of the absolute gamma function.
// Derived from SLEEF src/libm/sleefsimddp.c (gammak and sinpik), with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: MIT AND BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

mod data;
mod zeros;
use crate::precision::{exp_value, log_dd, madd, Dd};
use core::simd::prelude::*;

#[inline]
fn sinpi<const N: usize>(a: Simd<f64, N>) -> Dd<N> {
    // Reduction before multiplying by pi preserves precision near every pole.
    let ax = a.abs();
    let d = ax - crate::floor_f64(ax * Simd::splat(0.5)) * Simd::splat(2.0);
    let u = d * Simd::splat(4.0);
    let q = (u.cast::<i32>() + Simd::splat(1)) & Simd::splat(!1);
    let cosine = (q & Simd::splat(2)).simd_ne(Simd::splat(0)).cast::<i64>();
    let t = u - q.cast::<f64>();
    let s2 = Dd::product(t, t);
    let s = t * t;
    let coefficients = [
        [
            9.94480387626843774090208e-16,
            -2.02461120785182399295868e-14,
        ],
        [
            -3.89796226062932799164047e-13,
            6.948218305801794613277840e-12,
        ],
        [
            1.150115825399960352669010e-10,
            -1.75724749952853179952664e-09,
        ],
        [
            -2.46113695010446974953590e-08,
            3.133616889668683928784220e-07,
        ],
        [
            3.590860448590527540050620e-06,
            -3.65762041821615519203610e-05,
        ],
        [
            -0.000325991886927389905997954,
            0.0024903945701927185027435600,
        ],
    ];
    let mut p = cosine.select(
        Simd::splat(coefficients[0][0]),
        Simd::splat(coefficients[0][1]),
    );
    for c in &coefficients[1..] {
        p = madd(p, s, cosine.select(Simd::splat(c[0]), Simd::splat(c[1])));
    }
    let p = Dd::from(p * s).add(Dd::select(
        cosine,
        Dd::splat(0.0158543442438155018914259, -1.04693272280631521908845e-18),
        Dd::splat(-0.0807455121882807852484731, 3.61852475067037104849987e-18),
    ));
    let p = p.mul(s2).add(Dd::select(
        cosine,
        Dd::splat(-0.308425137534042437259529, -1.95698492133633550338345e-17),
        Dd::splat(0.785398163397448278999491, 3.06287113727155002607105e-17),
    ));
    let p = p.mul(Dd::select(cosine, s2, Dd::from(t)));
    let p = Dd::select(cosine, p.add_float(Simd::splat(1.0)), p);
    let negative =
        (q & Simd::splat(4)).simd_ne(Simd::splat(0)).cast::<i64>() ^ a.is_sign_negative();
    Dd::select(negative, p.neg(), p)
}

/// Return the compensated exponent and signed multiplier, for finite non-poles.
#[inline]
fn kernel<const N: usize>(a: Simd<f64, N>) -> (Dd<N>, Dd<N>) {
    let tiny = a.abs().simd_lt(Simd::splat(1.0e-306));
    let reflect = a.simd_lt(Simd::splat(0.5));
    let mut x = Dd::select(reflect, Dd::splat(1.0, 0.0).add_float(-a), Dd::from(a));
    x = Dd::select(tiny, Dd::splat(1.0, 0.0), x);
    let near_one = x.hi.simd_le(Simd::splat(1.1));
    let large = x.hi.simd_ge(Simd::splat(2.3));
    let shift = large & x.hi.simd_le(Simd::splat(7.0));
    let recurrence = if shift.any() {
        let mut product = x;
        for i in 1..=4 {
            product = product.mul(x.add_float(Simd::splat(i as f64))).normalize();
        }
        Dd::select(shift, product, Dd::splat(1.0, 0.0))
    } else {
        Dd::splat(1.0, 0.0)
    };
    x = Dd::select(shift, x.add_float(Simd::splat(5.0)), x);
    let center = near_one.select(Simd::splat(-1.0), Simd::splat(-2.0));
    let t = large.select(Simd::splat(1.0) / x.hi, x.add_float(center).normalize().hi);
    let coefficient = |c: [f64; 3]| {
        large.select(
            Simd::splat(c[0]),
            near_one.select(Simd::splat(c[1]), Simd::splat(c[2])),
        )
    };
    let t2 = t * t;
    let mut even = coefficient(data::COEFFICIENTS[0]);
    let mut odd = coefficient(data::COEFFICIENTS[1]);
    for i in (2..data::COEFFICIENTS.len()).step_by(2) {
        even = madd(even, t2, coefficient(data::COEFFICIENTS[i]));
        if i + 1 < data::COEFFICIENTS.len() {
            odd = madd(odd, t2, coefficient(data::COEFFICIENTS[i + 1]));
        }
    }
    let u = madd(odd, t, even);
    let stirling = x
        .add_float(Simd::splat(-0.5))
        .mul(log_dd(x))
        .sub(x)
        .add(Dd::splat(
            0.91893853320467278056,
            -3.8782941580672414498e-17,
        ));
    let z = Dd::product(u, t).add_float(near_one.select(
        Simd::splat(-0.4006856343865314862),
        Simd::splat(-0.06735230105319810201),
    ));
    let z = z.mul_float(t).add_float(near_one.select(
        Simd::splat(0.8224670334241132030),
        Simd::splat(0.3224670334241132030),
    ));
    let z = z
        .mul_float(t)
        .add_float(near_one.select(
            Simd::splat(-0.5772156649015328655),
            Simd::splat(0.4227843350984671345),
        ))
        .mul_float(t);
    let correction = Dd::select(
        large,
        Dd::product(u, t).add_float(Simd::splat(1.0)),
        Dd::splat(1.0, 0.0),
    );
    let mut logarithm = Dd::select(large, stirling, z);
    let mut numerator = correction;
    let mut denominator = recurrence;
    if reflect.any() {
        let sine = sinpi(a);
        numerator = Dd::select(reflect, recurrence, numerator);
        denominator = Dd::select(reflect, correction.mul(sine), denominator);
        logarithm = Dd::select(
            reflect,
            Dd::splat(1.1447298858494001639, 1.026595116270782638e-17).sub(logarithm),
            logarithm,
        );
    }
    let mut ratio = numerator.div(denominator);
    if tiny.any() {
        logarithm = Dd::select(
            tiny,
            Dd::splat(83.1776616671934334590333, 3.67103459631568507221878e-15),
            logarithm,
        );
        ratio = Dd::select(
            tiny,
            Dd::splat(1.0, 0.0).div(Dd::from(
                a * Simd::splat(1329227995784915872903807060280344576.0),
            )),
            ratio,
        );
    }
    (logarithm, ratio.normalize())
}

#[inline]
fn regular<const N: usize>(x: Simd<f64, N>) -> Mask<i64, N> {
    // Classification needs only equality to an integer, not truncation.
    // Adding a signed 2^52 rounds smaller magnitudes to integer spacing.
    let integer =
        if crate::backend::use_hardware_round_f64::<N>(crate::backend::RoundingMode::Directed) {
            crate::trunc_f64(x).simd_eq(x)
        } else {
            let shift = Simd::splat(4503599627370496.0).copysign(x);
            ((x + shift) - shift).simd_eq(x) | x.abs().simd_ge(Simd::splat(4503599627370496.0))
        };
    x.is_finite() & x.simd_ne(Simd::splat(0.0)) & !(x.simd_lt(Simd::splat(0.0)) & integer)
}

#[cold]
#[inline(never)]
fn near_zero<const N: usize>(x: Simd<f64, N>, mut value: Simd<f64, N>) -> Simd<f64, N> {
    for zero in zeros::ZEROS {
        let center = Simd::splat(zero.center);
        let hit = (x - center).abs().simd_le(Simd::splat(zero.radius));
        if hit.all() {
            return zero_series(x, zero);
        }
        if hit.any() {
            // Sparse corrections should not evaluate the expensive local
            // series in every inactive lane. Dense inputs keep the SIMD path.
            for lane in 0..N {
                if hit.test(lane) {
                    value[lane] = zero_series(Simd::<f64, 1>::splat(x[lane]), zero)[0];
                }
            }
        }
    }
    value
}

#[inline]
fn zero_series<const N: usize>(x: Simd<f64, N>, zero: &zeros::Zero) -> Simd<f64, N> {
    let t = (x - Simd::splat(zero.center)) / Simd::splat(zero.scale);
    // Higher terms are suppressed by |t| < 1/16. Only the last four
    // coefficients need compensation for cancellation near a root.
    let mut high = Simd::splat(zero.coefficients[20][0]);
    for c in zero.coefficients[4..20].iter().rev() {
        high = madd(high, t, Simd::splat(c[0]));
    }
    let mut p = Dd::from(high);
    for c in zero.coefficients[..4].iter().rev() {
        p = p.mul_float(t).add(Dd::splat(c[0], c[1])).normalize();
    }
    p.value()
}

/// Computes Gamma(x) for each lane. Negative integer poles return NaN.
#[inline]
pub fn tgamma_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let finite = regular(x);
    let (logarithm, ratio) = kernel(finite.select(x, Simd::splat(1.0)));
    // Unfused compensation has more temporaries. Combining the logarithms
    // keeps the ratio out of the exponential's register budget on that path,
    // and avoids intermediate overflow or underflow at extreme exponents.
    let result = if !crate::backend::use_hardware_fma_f64::<N>()
        || !logarithm.hi.abs().simd_lt(Simd::splat(700.0)).all()
    {
        let negative = ratio.hi.is_sign_negative();
        let magnitude = Dd::select(negative, ratio.neg(), ratio);
        let value = exp_value(logarithm.add(log_dd(magnitude)).normalize());
        negative.select(-value, value)
    } else {
        let exponential = exp_value(logarithm);
        madd(exponential, ratio.lo, exponential * ratio.hi)
    };
    let result =
        (x.simd_gt(Simd::splat(0.0)) & result.is_nan()).select(Simd::splat(f64::INFINITY), result);
    let exceptional = x.simd_eq(Simd::splat(0.0)).select(
        Simd::splat(f64::INFINITY).copysign(x),
        Simd::splat(f64::NAN),
    );
    let exceptional = x.simd_eq(Simd::splat(f64::INFINITY)).select(x, exceptional);
    finite.select(result, x.is_nan().select(x + x, exceptional))
}

/// Keep the rare f32 cancellation correction out of the ordinary path.
#[cold]
#[inline(never)]
fn correct_f32_near_zero<const N: usize>(x: Simd<f64, N>, value: Simd<f64, N>) -> Simd<f64, N> {
    let near_zero = x.simd_lt(Simd::splat(0.0)) & value.abs().simd_lt(Simd::splat(1.0e-4));
    near_zero.select(lgamma_f64(x), value)
}

/// Computes log(abs(Gamma(x))) for each lane, without global sign state.
#[inline]
pub fn lgamma_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let finite = regular(x);
    let (logarithm, ratio) = kernel(finite.select(x, Simd::splat(1.0)));
    let magnitude = Dd::select(ratio.hi.is_sign_negative(), ratio.neg(), ratio);
    let value = logarithm.add(log_dd(magnitude)).value();
    let value = value.is_nan().select(Simd::splat(f64::INFINITY), value);
    let value = if (x.simd_lt(Simd::splat(0.0)) & value.abs().simd_lt(Simd::splat(0.05))).any() {
        near_zero(x, value)
    } else {
        value
    };
    finite.select(value, x.is_nan().select(x + x, Simd::splat(f64::INFINITY)))
}

/// Computes Gamma(x) for each lane. Negative integer poles return NaN.
#[inline]
pub fn tgamma_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let a = x.cast::<f64>();
    let finite = regular(a);
    let (logarithm, negative) = kernel_f32(finite.select(a, Simd::splat(1.0)));
    let magnitude = crate::exp_f64(logarithm).cast::<f32>();
    let result = negative.cast::<i32>().select(-magnitude, magnitude);
    let exceptional = x.simd_eq(Simd::splat(0.0)).select(
        Simd::splat(f32::INFINITY).copysign(x),
        Simd::splat(f32::NAN),
    );
    let exceptional = x.simd_eq(Simd::splat(f32::INFINITY)).select(x, exceptional);
    finite
        .cast::<i32>()
        .select(result, x.is_nan().select(x + x, exceptional))
}

/// Computes log(abs(Gamma(x))) for each lane, without global sign state.
#[inline]
pub fn lgamma_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let a = x.cast::<f64>();
    let finite = regular(a);
    let (value, _) = kernel_f32(finite.select(a, Simd::splat(1.0)));
    let near_zero = a.simd_lt(Simd::splat(0.0)) & value.abs().simd_lt(Simd::splat(1.0e-4));
    let value = if near_zero.any() {
        correct_f32_near_zero(a, value)
    } else {
        value
    };
    let value = value.cast::<f32>();
    finite
        .cast::<i32>()
        .select(value, x.is_nan().select(x + x, Simd::splat(f32::INFINITY)))
}

// Single-precision outputs need only ordinary double arithmetic. Keeping the
// recurrence and reflection in double also covers every f32 subnormal.
#[inline]
fn kernel_f32<const N: usize>(a: Simd<f64, N>) -> (Simd<f64, N>, Mask<i64, N>) {
    let reflect = a.simd_lt(Simd::splat(0.5));
    let mut x = reflect.select(Simd::splat(1.0) - a, a);
    let near_one = x.simd_le(Simd::splat(1.1));
    let large = x.simd_ge(Simd::splat(2.3));
    let shift = large & x.simd_le(Simd::splat(7.0));
    let mut recurrence = x;
    for i in 1..=4 {
        recurrence *= x + Simd::splat(i as f64);
    }
    recurrence = shift.select(recurrence, Simd::splat(1.0));
    x = shift.select(x + Simd::splat(5.0), x);
    let t = large.select(
        Simd::splat(1.0) / x,
        x + near_one.select(Simd::splat(-1.0), Simd::splat(-2.0)),
    );
    let coefficient = |c: [f64; 3]| {
        large.select(
            Simd::splat(c[0]),
            near_one.select(Simd::splat(c[1]), Simd::splat(c[2])),
        )
    };
    let mut u = coefficient(data::COEFFICIENTS[0]);
    for &c in &data::COEFFICIENTS[1..] {
        u = madd(u, t, coefficient(c));
    }
    let stirling =
        (x - Simd::splat(0.5)) * crate::log_f64(x) - x + Simd::splat(0.91893853320467278056);
    let z = madd(
        u,
        t,
        near_one.select(
            Simd::splat(-0.4006856343865314862),
            Simd::splat(-0.06735230105319810201),
        ),
    );
    let z = madd(
        z,
        t,
        near_one.select(
            Simd::splat(0.8224670334241132030),
            Simd::splat(0.3224670334241132030),
        ),
    );
    let z = madd(
        z,
        t,
        near_one.select(
            Simd::splat(-0.5772156649015328655),
            Simd::splat(0.4227843350984671345),
        ),
    ) * t;
    let correction = large.select(madd(u, t, Simd::splat(1.0)), Simd::splat(1.0));
    let mut logarithm = large.select(stirling, z);
    let mut ratio = correction / recurrence;
    if reflect.any() {
        let ax = a.abs();
        let d = ax - crate::floor_f64(ax * Simd::splat(0.5)) * Simd::splat(2.0);
        let upper = d.simd_gt(Simd::splat(1.0));
        let d = upper.select(Simd::splat(2.0) - d, d);
        let d = d.simd_gt(Simd::splat(0.5)).select(Simd::splat(1.0) - d, d);
        let sine = crate::sin_f64(d * Simd::splat(core::f64::consts::PI));
        let sine = (upper ^ a.is_sign_negative()).select(-sine, sine);
        ratio = reflect.select(recurrence / (correction * sine), ratio);
        logarithm = reflect.select(Simd::splat(1.1447298858494002) - logarithm, logarithm);
    }
    let negative = ratio.is_sign_negative();
    (logarithm + crate::log_f64(ratio.abs()), negative)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tiny_negative_arguments_keep_their_sign() {
        let x = Simd::from_array([-f32::from_bits(0x000ce52b), -f32::MIN_POSITIVE]);
        let gamma = tgamma_f32(x);
        assert_eq!(gamma[0], f32::NEG_INFINITY);
        assert_eq!(gamma[1], 1.0 / x[1]);
        assert!(lgamma_f32(x).is_finite().all());
    }
}
