//! Hyperbolic functions and their inverses.
// sinh, cosh, and tanh based on SLEEF src/libm/sleefsimddp.c
// (xsinh_u35, xcosh_u35, xtanh_u35), with changes.
// The inverses use stable rearrangements of their defining identities.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use crate::precision::{exp_dd, Dd};
use core::simd::prelude::*;

/// Computes the hyperbolic sine for each lane.
#[inline]
pub fn sinh_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let a = ax.simd_min(Simd::splat(710.5));
    let e = crate::expm1_f64(a.simd_min(Simd::splat(700.0)));
    let small = Simd::splat(0.5) * (e + e / (e + Simd::splat(1.0)));
    // Squaring exp(x/2) extends the finite range beyond exp's overflow point.
    let near = ax.simd_lt(Simd::splat(20.0));
    let y = if near.all() {
        small
    } else {
        let t = exp_dd(Dd::from(a * Simd::splat(0.5)));
        let large = t.scale(Simd::splat(0.5)).mul(t).value();
        near.select(small, large)
    };
    let y = ax
        .simd_gt(Simd::splat(710.4758600739439))
        .select(Simd::splat(f64::INFINITY), y);
    let y = ax.simd_lt(Simd::splat(1.0e-8)).select(ax, y).copysign(x);
    x.is_nan().select(x + x, y)
}

/// Computes the hyperbolic cosine for each lane.
#[inline]
pub fn cosh_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let a = ax.simd_min(Simd::splat(710.5));
    let e = crate::exp_f64(a.simd_min(Simd::splat(700.0)));
    let small = Simd::splat(0.5) * e + Simd::splat(0.5) / e;
    let near = ax.simd_lt(Simd::splat(20.0));
    let y = if near.all() {
        small
    } else {
        let t = exp_dd(Dd::from(a * Simd::splat(0.5)));
        let large = t.scale(Simd::splat(0.5)).mul(t).value();
        near.select(small, large)
    };
    let y = ax
        .simd_gt(Simd::splat(710.4758600739439))
        .select(Simd::splat(f64::INFINITY), y);
    x.is_nan().select(x + x, y)
}

/// Computes the hyperbolic tangent for each lane.
#[inline]
pub fn tanh_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let a = ax.simd_min(Simd::splat(20.0));
    let e = crate::expm1_f64(a * Simd::splat(2.0));
    let y = e / (e + Simd::splat(2.0));
    let y = ax.simd_gt(Simd::splat(19.0)).select(Simd::splat(1.0), y);
    let y = ax.simd_lt(Simd::splat(1.0e-8)).select(ax, y).copysign(x);
    x.is_nan().select(x + x, y)
}

/// Computes the inverse hyperbolic sine for each lane.
#[inline]
pub fn asinh_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let a = ax.simd_min(Simd::splat(1.0e150));
    let a2 = a * a;
    let y = crate::log1p_f64(a + a2 / (Simd::splat(1.0) + crate::sqrt_f64(Simd::splat(1.0) + a2)));
    let large = ax.simd_gt(Simd::splat(1.0e150));
    let y = if large.any() {
        large.select(crate::log_f64(ax) + Simd::splat(core::f64::consts::LN_2), y)
    } else {
        y
    };
    let y = ax.simd_lt(Simd::splat(1.0e-8)).select(ax, y).copysign(x);
    x.is_nan().select(x + x, y)
}

/// Computes the inverse hyperbolic cosine for each lane (x >= 1).
#[inline]
pub fn acosh_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let a = x.simd_min(Simd::splat(1.0e150));
    let t = a - Simd::splat(1.0);
    let y = crate::log1p_f64(t + crate::sqrt_f64(t * (a + Simd::splat(1.0))));
    let large = x.simd_gt(Simd::splat(1.0e150));
    let y = if large.any() {
        large.select(crate::log_f64(x) + Simd::splat(core::f64::consts::LN_2), y)
    } else {
        y
    };
    x.simd_lt(Simd::splat(1.0))
        .select(Simd::splat(f64::NAN), x.is_nan().select(x + x, y))
}

/// Computes the inverse hyperbolic tangent for each lane (|x| <= 1).
#[inline]
pub fn atanh_f64<const N: usize>(x: Simd<f64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let y = Simd::splat(0.5) * crate::log1p_f64((ax + ax) / (Simd::splat(1.0) - ax));
    let y = ax.simd_lt(Simd::splat(1.0e-8)).select(ax, y).copysign(x);
    ax.simd_gt(Simd::splat(1.0))
        .select(Simd::splat(f64::NAN), x.is_nan().select(x + x, y))
}

/// Computes the hyperbolic sine for each lane.
#[inline]
pub fn sinh_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let ax = x.abs();
    let e = crate::expm1_f32(ax.simd_min(Simd::splat(80.0)));
    let y = Simd::splat(0.5) * (e + e / (e + Simd::splat(1.0)));
    let large = ax.simd_gt(Simd::splat(80.0));
    let y = if large.any() {
        large.select(sinh_f64(x.cast()).cast(), y.copysign(x))
    } else {
        y.copysign(x)
    };
    ax.simd_lt(Simd::splat(1.0e-4))
        .select(x, x.is_nan().select(x + x, y))
}

/// Computes the hyperbolic cosine for each lane.
#[inline]
pub fn cosh_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let ax = x.abs();
    let e = crate::exp_f32(ax.simd_min(Simd::splat(80.0)));
    let y = Simd::splat(0.5) * e + Simd::splat(0.5) / e;
    let large = ax.simd_gt(Simd::splat(80.0));
    let y = if large.any() {
        large.select(cosh_f64(x.cast()).cast(), y)
    } else {
        y
    };
    x.is_nan().select(x + x, y)
}

/// Computes the hyperbolic tangent for each lane.
#[inline]
pub fn tanh_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let ax = x.abs();
    let e = crate::expm1_f32(ax.simd_min(Simd::splat(10.0)) * Simd::splat(2.0));
    let y = (e / (e + Simd::splat(2.0))).copysign(x);
    let y = ax
        .simd_gt(Simd::splat(9.0))
        .select(Simd::splat(1.0).copysign(x), y);
    ax.simd_lt(Simd::splat(1.0e-4))
        .select(x, x.is_nan().select(x + x, y))
}

/// Computes the inverse hyperbolic sine for each lane.
#[inline]
pub fn asinh_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let ax = x.abs();
    let a = ax.simd_min(Simd::splat(1.0e18));
    let a2 = a * a;
    let y = crate::log1p_f32(a + a2 / (Simd::splat(1.0) + crate::sqrt_f32(Simd::splat(1.0) + a2)));
    let large = ax.simd_gt(Simd::splat(1.0e18));
    let y = if large.any() {
        large.select(crate::log_f32(ax) + Simd::splat(core::f32::consts::LN_2), y)
    } else {
        y
    };
    ax.simd_lt(Simd::splat(1.0e-4))
        .select(x, x.is_nan().select(x + x, y.copysign(x)))
}

/// Computes the inverse hyperbolic cosine for each lane (x >= 1).
#[inline]
pub fn acosh_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let a = x.simd_min(Simd::splat(1.0e18));
    let t = a - Simd::splat(1.0);
    let y = crate::log1p_f32(t + crate::sqrt_f32(t * (a + Simd::splat(1.0))));
    let large = x.simd_gt(Simd::splat(1.0e18));
    let y = if large.any() {
        large.select(crate::log_f32(x) + Simd::splat(core::f32::consts::LN_2), y)
    } else {
        y
    };
    x.simd_lt(Simd::splat(1.0))
        .select(Simd::splat(f32::NAN), x.is_nan().select(x + x, y))
}

/// Computes the inverse hyperbolic tangent for each lane (|x| <= 1).
#[inline]
pub fn atanh_f32<const N: usize>(x: Simd<f32, N>) -> Simd<f32, N> {
    let ax = x.abs();
    let y = Simd::splat(0.5) * crate::log1p_f32((ax + ax) / (Simd::splat(1.0) - ax));
    let y = ax.simd_lt(Simd::splat(1.0e-4)).select(ax, y).copysign(x);
    ax.simd_gt(Simd::splat(1.0))
        .select(Simd::splat(f32::NAN), x.is_nan().select(x + x, y))
}
