//! Scaled Euclidean magnitude.
// Based on SLEEF src/libm/sleefsimddp.c (xhypot_u35), with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use core::simd::prelude::*;

macro_rules! hypot {
    ($name:ident, $kind:ident, $sqrt:ident) => {
        /// Computes sqrt(x*x+y*y) without intermediate overflow or underflow.
        #[inline]
        pub fn $name<const N: usize>(x: Simd<$kind, N>, y: Simd<$kind, N>) -> Simd<$kind, N> {
            let ax = x.abs();
            let ay = y.abs();
            let hi = ax.simd_max(ay);
            let lo = ax.simd_min(ay);
            let ratio = lo / hi;
            let result = hi * crate::$sqrt(Simd::splat(1.0) + ratio * ratio);
            let result = lo.simd_eq(Simd::splat(0.0)).select(hi, result);
            let result = (x.is_nan() | y.is_nan()).select(x + y, result);
            (ax.is_infinite() | ay.is_infinite()).select(Simd::splat($kind::INFINITY), result)
        }
    };
}
hypot!(hypot_f32, f32, sqrt_f32);
hypot!(hypot_f64, f64, sqrt_f64);

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn exceptional_and_scaled_inputs() {
        let x = Simd::from_array([0.0, -0.0, f64::INFINITY, f64::MAX / 2.0, f64::from_bits(1)]);
        let y = Simd::from_array([-0.0, 0.0, f64::NAN, f64::MAX / 2.0, f64::from_bits(1)]);
        let result = hypot_f64(x, y).to_array();
        assert_eq!(result[0].to_bits(), 0);
        assert_eq!(result[1].to_bits(), 0);
        assert_eq!(result[2], f64::INFINITY);
        assert!(result[3].is_finite());
        assert_eq!(result[4].to_bits(), 1);
    }
}
