//! Real powers, with compensated logarithm and exponential kernels.
// Derived from SLEEF src/libm/sleefsimddp.c (xpow), with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: MIT AND BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use crate::precision::{exp_value, log_float_dd};
use core::simd::prelude::*;

/// Computes x raised to y for each lane, including integer powers of negative x.
#[inline]
pub fn pow_f64<const N: usize>(x: Simd<f64, N>, y: Simd<f64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let a = (ax.is_finite() & ax.simd_ne(Simd::splat(0.0))).select(ax, Simd::splat(1.0));
    // Beyond this limit every representable base other than 1 gives 0 or inf.
    let exponent = y.simd_clamp(Simd::splat(-1.0e20), Simd::splat(1.0e20));
    let d = log_float_dd(a).mul_float(exponent).normalize();
    let magnitude = exp_value(d);
    if (x.simd_gt(Simd::splat(0.0)) & x.is_finite() & y.is_finite()).all() {
        return magnitude;
    }
    let integer = crate::trunc_f64(y).simd_eq(y) & y.is_finite();
    let odd = integer
        & y.abs().simd_lt(Simd::splat(9007199254740992.0))
        & ((y.abs().cast::<u64>() & Simd::splat(1)).simd_ne(Simd::splat(0)));
    let negative = x.is_sign_negative() & odd;
    let mut result = negative.select(-magnitude, magnitude);
    result = (x.simd_lt(Simd::splat(0.0)) & !integer).select(Simd::splat(f64::NAN), result);
    let extreme = (ax.simd_gt(Simd::splat(1.0)) ^ y.is_sign_negative())
        .select(Simd::splat(f64::INFINITY), Simd::splat(0.0));
    let extreme = ax
        .simd_eq(Simd::splat(1.0))
        .select(Simd::splat(1.0), extreme);
    result = y.is_infinite().select(extreme, result);
    let zero_or_inf = (ax.simd_eq(Simd::splat(0.0)) ^ y.is_sign_negative())
        .select(Simd::splat(0.0), Simd::splat(f64::INFINITY));
    let zero_or_inf = negative.select(-zero_or_inf, zero_or_inf);
    result = (ax.simd_eq(Simd::splat(0.0)) | ax.is_infinite()).select(zero_or_inf, result);
    result = (x.is_nan() | y.is_nan()).select(x + y, result);
    (y.simd_eq(Simd::splat(0.0)) | x.simd_eq(Simd::splat(1.0))).select(Simd::splat(1.0), result)
}

/// Computes x raised to y for each lane, including integer powers of negative x.
#[inline]
pub fn pow_f32<const N: usize>(x: Simd<f32, N>, y: Simd<f32, N>) -> Simd<f32, N> {
    let ax = x.abs();
    let a = (ax.is_finite() & ax.simd_ne(Simd::splat(0.0))).select(ax, Simd::splat(1.0));
    // Double precision leaves ample error margin for the single-precision
    // result, including large exponents with a base close to one.
    let exponent = y
        .simd_clamp(Simd::splat(-1.0e12), Simd::splat(1.0e12))
        .cast::<f64>();
    let magnitude = crate::exp_f64(crate::log_f64(a.cast()) * exponent).cast::<f32>();
    if (x.simd_gt(Simd::splat(0.0)) & x.is_finite() & y.is_finite()).all() {
        return magnitude;
    }
    let integer = crate::trunc_f32(y).simd_eq(y) & y.is_finite();
    let odd = integer
        & y.abs().simd_lt(Simd::splat(16777216.0))
        & (y.abs().cast::<u32>() & Simd::splat(1)).simd_ne(Simd::splat(0));
    let negative = x.is_sign_negative() & odd;
    let mut result = negative.select(-magnitude, magnitude);
    result = (x.simd_lt(Simd::splat(0.0)) & !integer).select(Simd::splat(f32::NAN), result);
    let extreme = (ax.simd_gt(Simd::splat(1.0)) ^ y.is_sign_negative())
        .select(Simd::splat(f32::INFINITY), Simd::splat(0.0));
    let extreme = ax
        .simd_eq(Simd::splat(1.0))
        .select(Simd::splat(1.0), extreme);
    result = y.is_infinite().select(extreme, result);
    let zero_or_inf = (ax.simd_eq(Simd::splat(0.0)) ^ y.is_sign_negative())
        .select(Simd::splat(0.0), Simd::splat(f32::INFINITY));
    let zero_or_inf = negative.select(-zero_or_inf, zero_or_inf);
    result = (ax.simd_eq(Simd::splat(0.0)) | ax.is_infinite()).select(zero_or_inf, result);
    result = (x.is_nan() | y.is_nan()).select(x + y, result);
    (y.simd_eq(Simd::splat(0.0)) | x.simd_eq(Simd::splat(1.0))).select(Simd::splat(1.0), result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bases_adjacent_to_one_with_large_exponents() {
        // References computed with 100 decimal digits. Rounding log(x) to
        // ordinary f64 precision before multiplication loses these results.
        let x = Simd::from_array([
            f64::from_bits(0x3ff0000000000001),
            f64::from_bits(0x3fefffffffffffff),
        ]);
        let y = Simd::from_array([1.0e18, -1.0e18]);
        let expected = [2.7086111089766717e96_f64, 1.6457858636459278e48];
        for (got, expected) in pow_f64(x, y).to_array().into_iter().zip(expected) {
            assert!(got.to_bits().abs_diff(expected.to_bits()) <= 3);
        }
        let x = Simd::from_array([f32::from_bits(0x3f800001), f32::from_bits(0x3f7fffff)]);
        let y = Simd::from_array([5.0e8, -1.0e9]);
        let expected = [7.6907160044557845e25_f32, 7.6907570484613485e25];
        for (got, expected) in pow_f32(x, y).to_array().into_iter().zip(expected) {
            assert!(got.to_bits().abs_diff(expected.to_bits()) <= 3);
        }
    }

    #[test]
    fn negative_bases_and_identity_cases() {
        let x = Simd::from_array([-2.0, -2.0, -0.0, -0.0, f64::NAN, 1.0, -1.0]);
        let y = Simd::from_array([3.0, 0.5, 3.0, -3.0, 0.0, f64::NAN, f64::INFINITY]);
        let r = pow_f64(x, y).to_array();
        assert!((r[0] + 8.0).abs() < 1.0e-14);
        assert!(r[1].is_nan());
        assert_eq!(r[2].to_bits(), (-0.0_f64).to_bits());
        assert_eq!(r[3], f64::NEG_INFINITY);
        assert_eq!(&r[4..], &[1.0, 1.0, 1.0]);
    }
}
