//! Internal compensated arithmetic for kernels that need extra precision.
// Derived from SLEEF src/common/dd.h and src/libm/sleefsimddp.c, with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: MIT AND BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use core::simd::prelude::*;
use std::simd::StdFloat;
mod log_table;

#[inline]
pub(crate) fn madd<const N: usize>(
    a: Simd<f64, N>,
    b: Simd<f64, N>,
    c: Simd<f64, N>,
) -> Simd<f64, N> {
    if crate::backend::use_hardware_fma_f64::<N>() {
        a.mul_add(b, c)
    } else {
        a * b + c
    }
}

#[inline]
pub(crate) fn madd_f32<const N: usize>(
    a: Simd<f32, N>,
    b: Simd<f32, N>,
    c: Simd<f32, N>,
) -> Simd<f32, N> {
    if crate::backend::use_hardware_fma_f32::<N>() {
        a.mul_add(b, c)
    } else {
        a * b + c
    }
}

#[inline]
pub(crate) fn scale_f32<const N: usize>(x: Simd<f32, N>, exponent: Simd<i32, N>) -> Simd<f32, N> {
    let first = exponent.simd_clamp(Simd::splat(-126), Simd::splat(127));
    let second = exponent - first;
    let a = Simd::from_bits(((first + Simd::splat(127)).cast::<u32>()) << 23);
    let b = Simd::from_bits(((second + Simd::splat(127)).cast::<u32>()) << 23);
    (x * b) * a
}

#[derive(Clone, Copy)]
pub(crate) struct Dd<const N: usize> {
    pub hi: Simd<f64, N>,
    pub lo: Simd<f64, N>,
}

impl<const N: usize> Dd<N> {
    #[inline]
    pub fn new(hi: Simd<f64, N>, lo: Simd<f64, N>) -> Self {
        Self { hi, lo }
    }
    #[inline]
    pub fn from(hi: Simd<f64, N>) -> Self {
        Self::new(hi, Simd::splat(0.0))
    }
    #[inline]
    pub fn splat(hi: f64, lo: f64) -> Self {
        Self::new(Simd::splat(hi), Simd::splat(lo))
    }
    #[inline]
    pub fn value(self) -> Simd<f64, N> {
        self.hi + self.lo
    }
    #[inline]
    pub fn normalize(self) -> Self {
        let hi = self.hi + self.lo;
        Self::new(hi, (self.hi - hi) + self.lo)
    }
    #[inline]
    pub fn neg(self) -> Self {
        Self::new(-self.hi, -self.lo)
    }
    #[inline]
    pub fn select(mask: Mask<i64, N>, yes: Self, no: Self) -> Self {
        Self::new(mask.select(yes.hi, no.hi), mask.select(yes.lo, no.lo))
    }
    #[inline]
    pub fn add(self, other: Self) -> Self {
        let hi = self.hi + other.hi;
        let v = hi - self.hi;
        let error = (self.hi - (hi - v)) + (other.hi - v);
        Self::new(hi, error + (self.lo + other.lo))
    }
    #[inline]
    pub fn add_float(self, other: Simd<f64, N>) -> Self {
        self.add(Self::from(other))
    }
    #[inline]
    pub fn sub(self, other: Self) -> Self {
        self.add(other.neg())
    }
    #[inline]
    pub fn scale(self, factor: Simd<f64, N>) -> Self {
        Self::new(self.hi * factor, self.lo * factor)
    }
    #[inline]
    pub fn product(a: Simd<f64, N>, b: Simd<f64, N>) -> Self {
        let hi = a * b;
        let lo = if crate::backend::use_hardware_fma_f64::<N>() {
            a.mul_add(b, -hi)
        } else {
            // Bit splitting avoids the overflow of Dekker's multiplying split.
            let ah = Simd::<f64, N>::from_bits(a.to_bits() & Simd::splat(!((1_u64 << 27) - 1)));
            let bh = Simd::<f64, N>::from_bits(b.to_bits() & Simd::splat(!((1_u64 << 27) - 1)));
            let al = a - ah;
            let bl = b - bh;
            (((ah * bh - hi) + al * bh) + ah * bl) + al * bl
        };
        Self::new(hi, lo)
    }
    #[inline]
    pub fn mul(self, other: Self) -> Self {
        let p = Self::product(self.hi, other.hi);
        Self::new(p.hi, madd(self.hi, other.lo, madd(self.lo, other.hi, p.lo)))
    }
    #[inline]
    pub fn mul_float(self, other: Simd<f64, N>) -> Self {
        let p = Self::product(self.hi, other);
        Self::new(p.hi, madd(self.lo, other, p.lo))
    }
    #[inline]
    pub fn square(self) -> Self {
        let p = Self::product(self.hi, self.hi);
        Self::new(p.hi, madd(self.hi, self.lo + self.lo, p.lo))
    }
    #[inline]
    pub fn div(self, other: Self) -> Self {
        let q = self.hi / other.hi;
        let residual = if crate::backend::use_hardware_fma_f64::<N>() {
            (-q).mul_add(other.hi, self.hi)
        } else {
            let p = Self::product(q, other.hi);
            // The high subtraction is exact: q*other.hi is close to self.hi.
            (self.hi - p.hi) - p.lo
        };
        Self::new(q, (residual + madd(-q, other.lo, self.lo)) / other.hi)
    }
}

/// Scale by a power of two without creating an infinite or subnormal factor.
#[inline]
pub(crate) fn scale<const N: usize>(x: Simd<f64, N>, exponent: Simd<i64, N>) -> Simd<f64, N> {
    // All internal exponent ranges fit in i32. Narrow comparisons avoid
    // emulated i64 clamping on implementations with smaller SIMD widths.
    let exponent = exponent.cast::<i32>();
    let first = exponent.simd_clamp(Simd::splat(-1022), Simd::splat(1023));
    let second = exponent - first;
    let a = Simd::from_bits(((first + Simd::splat(1023)).cast::<u64>()) << 52);
    let b = Simd::from_bits(((second + Simd::splat(1023)).cast::<u64>()) << 52);
    (x * b) * a
}

/// Normalize a positive finite value to [0.5, 1), including subnormals.
#[inline]
pub(crate) fn frexp<const N: usize>(x: Simd<f64, N>) -> (Simd<f64, N>, Simd<i64, N>) {
    let small = x.simd_lt(Simd::splat(f64::MIN_POSITIVE));
    let a = small.select(x * Simd::splat(18014398509481984.0), x);
    let bits = a.to_bits();
    let e = (bits >> 52).cast::<i64>()
        - Simd::splat(1022)
        - small.select(Simd::splat(54), Simd::splat(0));
    let m = Simd::from_bits(
        (bits & Simd::splat(0x000f_ffff_ffff_ffff)) | Simd::splat(0x3fe0_0000_0000_0000),
    );
    (m, e)
}

#[inline]
pub(crate) fn polynomial<const N: usize>(x: Simd<f64, N>, coefficients: &[f64]) -> Simd<f64, N> {
    let x2 = x * x;
    let mut even = Simd::splat(coefficients[0]);
    let mut odd = Simd::splat(coefficients[1]);
    for i in (2..coefficients.len()).step_by(2) {
        even = madd(even, x2, Simd::splat(coefficients[i]));
        if i + 1 < coefficients.len() {
            odd = madd(odd, x2, Simd::splat(coefficients[i + 1]));
        }
    }
    if coefficients.len() % 2 == 0 {
        madd(even, x, odd)
    } else {
        madd(odd, x, even)
    }
}

/// Extra-precision logarithm, including a small low input component.
#[inline]
pub(crate) fn log_dd<const N: usize>(d: Dd<N>) -> Dd<N> {
    if crate::backend::use_hardware_fma_f64::<N>() {
        log_series_dd::<N, true>(d)
    } else {
        log_float_dd(d.hi).add_float(d.lo / d.hi).normalize()
    }
}

/// Table reduction for a positive finite floating input. The two intervals
/// next to one have reciprocal 1, preserving tiny logarithms for pow.
#[inline]
pub(crate) fn log_float_dd<const N: usize>(x: Simd<f64, N>) -> Dd<N> {
    if crate::backend::use_hardware_fma_f64::<N>() {
        log_series_dd::<N, false>(Dd::from(x))
    } else {
        log_table_dd(x)
    }
}

// Keep the table reducer's temporaries out of its callers' register budget.
#[inline(never)]
fn log_table_dd<const N: usize>(x: Simd<f64, N>) -> Dd<N> {
    let (m, e) = frexp(x);
    let upper = m.simd_lt(Simd::splat(0.75));
    let m = upper.select(m + m, m);
    let e = e - upper.select(Simd::splat(1), Simd::splat(0));
    // floor((m - .75) * 128), extracted directly from the two mantissa
    // ranges. This avoids a saturating float-to-usize conversion per lane.
    let bits = m.to_bits();
    let index = upper
        .select(
            (bits >> 45) - Simd::splat((1023_u64 << 7) - 32),
            (bits >> 46) - Simd::splat((1022_u64 << 6) + 32),
        )
        .cast::<usize>();
    let (log_hi, packed) = crate::table::lookup_pairs(&log_table::TABLE, index);
    let inverse =
        (packed & Simd::splat(255)).cast::<i32>().cast::<f64>() * Simd::splat(1.0 / 128.0);
    let log_hi = Simd::from_bits(log_hi);
    let log_lo = Simd::from_bits(packed & Simd::splat(!255));
    // The reciprocal has eight significant bits. Splitting the mantissa
    // makes both products exact without requiring an FMA or a division.
    let high = Simd::<f64, N>::from_bits(m.to_bits() & Simd::splat(!((1_u64 << 27) - 1)));
    // Both products are exact. If the low component is larger, these
    // dyadic pieces sum exactly; otherwise fast normalization applies.
    let r = Dd::new(high * inverse - Simd::splat(1.0), (m - high) * inverse).normalize();
    let r2 = r.square();
    let mut p = Simd::splat(1.0 / 11.0);
    for c in [
        -1.0 / 10.0,
        1.0 / 9.0,
        -1.0 / 8.0,
        1.0 / 7.0,
        -1.0 / 6.0,
        1.0 / 5.0,
        -1.0 / 4.0,
        1.0 / 3.0,
    ] {
        p = madd(p, r.hi, Simd::splat(c));
    }
    let reduced = r
        .add(r2.scale(Simd::splat(-0.5)))
        .add_float((r.hi * r.hi * r.hi) * p);
    let e = e.cast::<i32>().cast::<f64>();
    // The high ln(2) split has enough trailing zeros that this integer
    // product is exact throughout the f64 exponent range.
    let exponent = Dd::new(
        e * Simd::splat(0.69314718055966295651160180568695068359375),
        e * Simd::splat(2.82352905630315771225884481750134360255e-13),
    );
    exponent
        .add(Dd::new(log_hi, log_lo))
        .add(reduced)
        .normalize()
}

/// Arithmetic reduction for implementations with cheap compensated products.
#[inline]
fn log_series_dd<const N: usize, const LOW: bool>(d: Dd<N>) -> Dd<N> {
    let (m, e) = frexp(d.hi);
    let upper = m.simd_lt(Simd::splat(0.75));
    let m = upper.select(m + m, m);
    let e = e - upper.select(Simd::splat(1), Simd::splat(0));
    let z = if LOW {
        let m = Dd::new(m, scale(d.lo, -e));
        m.add_float(Simd::splat(-1.0))
            .div(m.add_float(Simd::splat(1.0)))
    } else {
        Dd::from(m - Simd::splat(1.0)).div(Dd::from(m).add_float(Simd::splat(1.0)))
    }
    .normalize();
    let z2 = z.square();
    let p = polynomial(
        z2.hi,
        &[
            0.116255524079935043668677,
            0.103239680901072952701192,
            0.117754809412463995466069,
            0.13332981086846273921509,
            0.153846227114512262845736,
            0.181818180850050775676507,
            0.222222222230083560345903,
            0.285714285714249172087875,
            0.400000000000000077715612,
        ],
    );
    let e = e.cast::<i32>().cast::<f64>();
    let logarithm = Dd::new(
        e * Simd::splat(0.69314718055966295651160180568695068359375),
        e * Simd::splat(2.82352905630315771225884481750134360255e-13),
    );
    let z3 = z2.mul(z);
    logarithm
        .add(z.scale(Simd::splat(2.0)))
        .add(z3.mul(Dd::splat(
            0.666666666666666629659233,
            3.80554962542412056336616e-17,
        )))
        .add(z3.mul(z2).mul_float(p))
        .normalize()
}

/// Extra-precision exponential, retaining the input's low component.
#[inline]
pub(crate) fn exp_dd<const N: usize>(d: Dd<N>) -> Dd<N> {
    let regular = d.hi.simd_ge(Simd::splat(-746.0)) & d.hi.simd_le(Simd::splat(710.0));
    let d0 = Dd::select(regular, d, Dd::splat(0.0, 0.0));
    let shift = Simd::splat(6755399441055744.0).copysign(d0.hi);
    let q = (d0.value() * Simd::splat(core::f64::consts::LOG2_E) + shift) - shift;
    let s = d0
        .add_float(q * Simd::splat(-0.69314718055966295651160180568695068359375))
        .add_float(q * Simd::splat(-2.82352905630315771225884481750134360255e-13))
        .normalize();
    let s2 = s.square();
    let s4 = s2.square();
    let p = polynomial(
        s.hi,
        &[
            0.1602472219709932072e-9,
            0.2092255183563157007e-8,
            0.2505230023782644465e-7,
            0.2755724800902135303e-6,
            0.2755731892386044373e-5,
            0.2480158735605815065e-4,
            0.1984126984148071858e-3,
            0.1388888888886763255e-2,
            0.8333333333333347095e-2,
            0.4166666666666669905e-1,
        ],
    );
    let t = s
        .mul_float(Simd::splat(0.1666666666666666574))
        .add_float(Simd::splat(0.5));
    let t = t.mul(s).add_float(Simd::splat(1.0));
    let t = t
        .mul(s)
        .add_float(Simd::splat(1.0))
        .add(s4.mul_float(p))
        .normalize();
    let q = q.cast::<i32>().cast::<i64>();
    let result = Dd::new(scale(t.hi, q), scale(t.lo, q));
    let exceptional =
        d.hi.simd_lt(Simd::splat(0.0))
            .select(Simd::splat(0.0), Simd::splat(f64::INFINITY));
    Dd::select(
        regular,
        result,
        Dd::from(d.hi.is_nan().select(d.hi, exceptional)),
    )
}

/// Exponential of a compensated argument when only one output component is
/// needed. Keep the reduction's low part, then correct the ordinary polynomial.
#[inline]
pub(crate) fn exp_value<const N: usize>(d: Dd<N>) -> Simd<f64, N> {
    let regular = d.hi.simd_ge(Simd::splat(-746.0)) & d.hi.simd_le(Simd::splat(710.0));
    let a = Dd::select(regular, d, Dd::splat(0.0, 0.0));
    let shift = Simd::splat(6755399441055744.0).copysign(a.hi);
    let q = (a.value() * Simd::splat(core::f64::consts::LOG2_E) + shift) - shift;
    // q times the truncated high ln(2) is exact, as is the high subtraction
    // by Sterbenz's lemma. Only the small low correction needs rounding.
    let r = Dd::new(
        a.hi - q * Simd::splat(0.69314718055966295651160180568695068359375),
        a.lo - q * Simd::splat(2.82352905630315771225884481750134360255e-13),
    )
    .normalize();
    let p = polynomial(
        r.hi,
        &[
            2.08860621107283687536341e-9,
            2.51112930892876518610661e-8,
            2.75573911234900471893338e-7,
            2.75572362911928827629423e-6,
            2.4801587159235472998791e-5,
            0.000198412698960509205564975,
            0.00138888888889774492207962,
            0.00833333333331652721664984,
            0.0416666666666665047591422,
            0.166666666666666851703837,
        ],
    );
    let r2 = r.hi * r.hi;
    let u = r.hi + madd(r2, Simd::splat(0.5), (r2 * r.hi) * p);
    let e = Simd::splat(1.0) + u;
    let value = scale(madd(e, r.lo, e), q.cast::<i32>().cast());
    let exceptional =
        d.hi.simd_lt(Simd::splat(0.0))
            .select(Simd::splat(0.0), Simd::splat(f64::INFINITY));
    regular.select(value, d.hi.is_nan().select(d.hi, exceptional))
}
