//! Exact floating remainders using compensated quotient reduction.
// Based on SLEEF src/libm/sleefsimddp.c (xfmod, xremainder), with changes and
// extended for remquo.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use crate::precision::{frexp, scale, Dd};
use core::simd::prelude::*;
use std::simd::StdFloat;

#[inline]
fn signed_quotient<const N: usize>(q: Simd<i32, N>, negative: Mask<i32, N>) -> Simd<i32, N> {
    let q = q & Simd::splat(7);
    negative.select(-q, q)
}

// Returning only the remainder avoids an unused quotient in the return buffer
// when this reducer is not inlined. QUOTIENT=false also removes the output argument.
#[inline]
fn reduce<const N: usize, const NEAREST: bool, const QUOTIENT: bool>(
    x: Simd<f64, N>,
    y: Simd<f64, N>,
    quotient_out: &mut Simd<i32, N>,
) -> Simd<f64, N> {
    let ax = x.abs();
    let ay = y.abs();
    let quotient = ax / ay;
    let quick = ax.simd_lt(Simd::splat(f64::MAX * 0.5))
        & ay.is_finite()
        & ay.simd_ge(Simd::splat(f64::MIN_POSITIVE * 2.0))
        & quotient.simd_lt(Simd::splat(1125899906842624.0));
    if quick.all() {
        let mut q = crate::trunc_f64(quotient);
        let product = Dd::product(q, ay);
        // q is the floor or one integer above it. Cancellation makes both
        // subtractions exact, and the residual has no more bits than y.
        let mut r = (ax - product.hi) - product.lo;
        let below = r.simd_lt(Simd::splat(0.0));
        r = below.select(r + ay, r);
        q -= below.select(Simd::splat(1.0), Simd::splat(0.0));
        if NEAREST {
            let half = ay * Simd::splat(0.5);
            let odd = (q.cast::<u64>() & Simd::splat(1)).simd_ne(Simd::splat(0));
            let subtract = r.simd_gt(half) | (r.simd_eq(half) & odd);
            r = subtract.select(r - ay, r);
            if QUOTIENT {
                q += subtract.select(Simd::splat(1.0), Simd::splat(0.0));
            }
        }
        if QUOTIENT {
            *quotient_out = signed_quotient(
                (q.cast::<u64>() & Simd::splat(7)).cast(),
                (x.is_sign_negative() ^ y.is_sign_negative()).cast(),
            );
        }
        return Simd::from_bits(r.to_bits() ^ (x.to_bits() & Simd::splat(1_u64 << 63)));
    }
    let valid = x.is_finite() & y.is_finite() & y.simd_ne(Simd::splat(0.0));
    let ax = valid.select(x.abs(), Simd::splat(1.0));
    let ay = valid.select(y.abs(), Simd::splat(1.0));
    let (mx, mut ex) = frexp(ax);
    let (my, ey) = frexp(ay);
    let divisor_exponent = ey + Simd::splat(if NEAREST { 1 } else { 0 });
    let mut r = Dd::from(mx);
    let mut quotient = Simd::<i32, N>::splat(0);
    // Each quotient removes up to 50 exponent bits. Products and residuals
    // retain their low component, including when x/y overflows.
    loop {
        let gap = ex - divisor_exponent;
        let active = gap.simd_gt(Simd::splat(0))
            | (gap.simd_eq(Simd::splat(0))
                & r.add_float(-my).normalize().hi.simd_ge(Simd::splat(0.0)));
        let active = active & r.hi.simd_ne(Simd::splat(0.0));
        if !active.any() {
            break;
        }
        let chunk = gap.simd_clamp(Simd::splat(0), Simd::splat(50));
        let denominator = scale(my, -chunk);
        let mut q = crate::trunc_f64(r.hi / denominator);
        let mut next = r.sub(Dd::product(q, denominator)).normalize();
        // Floating division can round across an integer quotient boundary.
        let below = next.hi.simd_lt(Simd::splat(0.0));
        next = Dd::select(below, next.add_float(denominator), next);
        let above = next
            .add_float(-denominator)
            .normalize()
            .hi
            .simd_ge(Simd::splat(0.0));
        next = Dd::select(above, next.add_float(-denominator), next).normalize();
        if QUOTIENT {
            q += above.select(Simd::splat(1.0), Simd::splat(0.0))
                - below.select(Simd::splat(1.0), Simd::splat(0.0));
            // This chunk removes q * 2^(ex-ey-chunk) multiples of y.
            // Higher shifts cannot affect the three low quotient bits.
            let shift = ex - ey - chunk;
            let bits = (q.cast::<u64>() & Simd::splat(7)).cast::<i32>()
                << shift
                    .simd_clamp(Simd::splat(0), Simd::splat(3))
                    .cast::<i32>();
            quotient += (active & shift.simd_lt(Simd::splat(3)))
                .cast::<i32>()
                .select(bits, Simd::splat(0));
            quotient &= Simd::splat(7);
        }
        next = Dd::select(active, next, r);
        let (mantissa, adjustment) = frexp(next.hi);
        let nonzero = active & next.hi.simd_ne(Simd::splat(0.0));
        r = Dd::select(
            nonzero,
            Dd::new(mantissa, scale(next.lo, -adjustment)),
            next,
        );
        ex += nonzero.select(adjustment, Simd::splat(0));
    }
    let mut result = scale(r.value(), ex);
    if NEAREST {
        let gap = ex - ey;
        let a = Dd::new(
            scale(r.hi, gap.simd_clamp(Simd::splat(-1), Simd::splat(1))),
            scale(r.lo, gap.simd_clamp(Simd::splat(-1), Simd::splat(1))),
        );
        let half = my * Simd::splat(0.5);
        let twice = a
            .sub(Dd::product(my, Simd::splat(1.5)))
            .normalize()
            .hi
            .simd_ge(Simd::splat(0.0));
        let once = a.add_float(-half).normalize().hi.simd_gt(Simd::splat(0.0)) & !twice;
        let q = twice.select(
            Simd::splat(2.0),
            once.select(Simd::splat(1.0), Simd::splat(0.0)),
        );
        let adjusted = scale(a.sub(Dd::product(q, my)).value(), ey);
        let adjust = gap.simd_ge(Simd::splat(-1));
        result = adjust.select(adjusted, result);
        if QUOTIENT {
            quotient += adjust.cast::<i32>().select(q.cast::<i32>(), Simd::splat(0));
        }
    }
    // Apply the dividend's sign by xor: a nearest remainder may be negative.
    result = Simd::from_bits(result.to_bits() ^ (x.to_bits() & Simd::splat(1_u64 << 63)));
    result = x.simd_eq(Simd::splat(0.0)).select(x, result);
    let exceptional = (y.is_infinite() & x.is_finite()).select(x, Simd::splat(f64::NAN));
    if QUOTIENT {
        quotient = signed_quotient(
            quotient,
            (x.is_sign_negative() ^ y.is_sign_negative()).cast(),
        );
        *quotient_out = valid.cast::<i32>().select(quotient, Simd::splat(0));
    }
    valid.select(result, exceptional)
}

/// Computes x-y*trunc(x/y) exactly for each lane, including overflowing ratios.
#[inline]
pub fn fmod_f64<const N: usize>(x: Simd<f64, N>, y: Simd<f64, N>) -> Simd<f64, N> {
    reduce::<N, false, false>(x, y, &mut Simd::splat(0))
}

/// Computes the IEEE remainder, choosing the nearest even integer quotient.
#[inline]
pub fn remainder_f64<const N: usize>(x: Simd<f64, N>, y: Simd<f64, N>) -> Simd<f64, N> {
    reduce::<N, true, false>(x, y, &mut Simd::splat(0))
}

/// Computes x-y*trunc(x/y) exactly for each lane, including overflowing ratios.
#[inline]
pub fn fmod_f32<const N: usize>(x: Simd<f32, N>, y: Simd<f32, N>) -> Simd<f32, N> {
    reduce_f32::<N, false, false>(x, y, &mut Simd::splat(0))
}

/// Computes the IEEE remainder, choosing the nearest even integer quotient.
#[inline]
pub fn remainder_f32<const N: usize>(x: Simd<f32, N>, y: Simd<f32, N>) -> Simd<f32, N> {
    reduce_f32::<N, true, false>(x, y, &mut Simd::splat(0))
}

/// Returns the IEEE remainder and the signed low three bits of the quotient.
///
/// The quotient is rounded to the nearest integer, with ties to even. Its
/// returned magnitude is modulo 8 and its sign follows x/y. Invalid inputs
/// return a NaN remainder and a zero quotient; finite x and infinite y return
/// x and a zero quotient. A zero remainder preserves the sign of x.
#[inline]
pub fn remquo_f64<const N: usize>(
    x: Simd<f64, N>,
    y: Simd<f64, N>,
) -> (Simd<f64, N>, Simd<i32, N>) {
    let mut quotient = Simd::splat(0);
    let remainder = reduce::<N, true, true>(x, y, &mut quotient);
    (remainder, quotient)
}

/// Returns the IEEE remainder and the signed low three bits of the quotient.
///
/// The quotient is rounded to the nearest integer, with ties to even. Its
/// returned magnitude is modulo 8 and its sign follows x/y. Invalid inputs
/// return a NaN remainder and a zero quotient; finite x and infinite y return
/// x and a zero quotient. A zero remainder preserves the sign of x.
#[inline]
pub fn remquo_f32<const N: usize>(
    x: Simd<f32, N>,
    y: Simd<f32, N>,
) -> (Simd<f32, N>, Simd<i32, N>) {
    let mut quotient = Simd::splat(0);
    let remainder = reduce_f32::<N, true, true>(x, y, &mut quotient);
    (remainder, quotient)
}

#[inline]
fn reduce_f32<const N: usize, const NEAREST: bool, const QUOTIENT: bool>(
    x: Simd<f32, N>,
    y: Simd<f32, N>,
    quotient_out: &mut Simd<i32, N>,
) -> Simd<f32, N> {
    let ax = x.abs();
    let ay = y.abs();
    let quotient = ax / ay;
    let quick = x.is_finite() & y.is_finite() & quotient.simd_lt(Simd::splat(4194304.0));
    if !quick.all() {
        return reduce::<N, NEAREST, QUOTIENT>(x.cast(), y.cast(), quotient_out).cast();
    }
    let mut q = crate::trunc_f32(quotient);
    let mut r = if crate::backend::use_hardware_fma_f32::<N>() {
        (-q).mul_add(ay, ax)
    } else {
        // A bounded integer times an f32 significand fits exactly in f64.
        (ax.cast::<f64>() - q.cast::<f64>() * ay.cast::<f64>()).cast::<f32>()
    };
    let below = r.simd_lt(Simd::splat(0.0));
    r = below.select(r + ay, r);
    q -= below.select(Simd::splat(1.0), Simd::splat(0.0));
    if NEAREST {
        // Comparing the two halves avoids underflow for subnormal divisors.
        let complement = ay - r;
        let odd = (q.cast::<u32>() & Simd::splat(1)).simd_ne(Simd::splat(0));
        let subtract = r.simd_gt(complement) | (r.simd_eq(complement) & odd);
        r = subtract.select(r - ay, r);
        if QUOTIENT {
            q += subtract.select(Simd::splat(1.0), Simd::splat(0.0));
        }
    }
    if QUOTIENT {
        *quotient_out = signed_quotient(q.cast(), x.is_sign_negative() ^ y.is_sign_negative());
    }
    Simd::from_bits(r.to_bits() ^ (x.to_bits() & Simd::splat(1_u32 << 31)))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn infinite_divisors_preserve_the_dividend() {
        let x = Simd::from_array([-0.0, 2.0, -3.0, f64::MIN_POSITIVE]);
        let y = Simd::from_array([
            f64::NEG_INFINITY,
            f64::INFINITY,
            f64::NEG_INFINITY,
            f64::INFINITY,
        ]);
        assert_eq!(fmod_f64(x, y).to_bits(), x.to_bits());
        assert_eq!(remainder_f64(x, y).to_bits(), x.to_bits());
    }
    #[test]
    fn rounded_three_halves_is_below_the_exact_boundary() {
        let y = f64::from_bits(0x3ff0000000000003);
        let x = y * 1.5;
        assert_eq!(
            remainder_f64(Simd::<f64, 1>::splat(x), Simd::splat(y))[0],
            x - y
        );
    }

    #[test]
    fn ties_signed_zero_and_extreme_ratios() {
        let x = Simd::from_array([1.0, 3.0, 5.0, 7.0, -4.0, f64::MAX, f64::MAX]);
        let y = Simd::from_array([
            2.0,
            2.0,
            2.0,
            2.0,
            2.0,
            f64::from_bits(3),
            f64::MIN_POSITIVE,
        ]);
        let r = remainder_f64(x, y).to_array();
        assert_eq!(&r[..4], &[1.0, -1.0, 1.0, -1.0]);
        assert_eq!(r[4].to_bits(), (-0.0_f64).to_bits());
        assert_eq!(r[6], 0.0);
        for i in 0..7 {
            assert_eq!(fmod_f64(x, y)[i].to_bits(), (x[i] % y[i]).to_bits());
        }
    }

    macro_rules! remquo_tests {
        ($kind:ident, $function:ident) => {
            paste::paste! {
                #[test]
                fn [<remquo_ties_signs_and_wraparound_ $kind>]() {
                    let x = Simd::from_array([1.0, 3.0, 5.0, 7.0, 15.0, -29.0, 29.0, -4.0]);
                    let y = Simd::from_array([2.0, 2.0, 2.0, 2.0, 2.0, 3.0, -3.0, 2.0]);
                    let (r, q) = $function(x, y);
                    let expected = Simd::<$kind, 8>::from_array([1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -0.0]);
                    assert_eq!(r.to_bits(), expected.to_bits());
                    assert_eq!(q.to_array(), [0, 2, 2, 4, 0, -2, -2, -2]);

                    // Rounded 1.5*y lies just below the exact tie for this y.
                    let y = Simd::<$kind, 1>::splat($kind::from_bits((1.0 as $kind).to_bits() + 3));
                    let x = y * Simd::splat(1.5);
                    let (r, q) = $function(x, y);
                    assert_eq!(r, x - y);
                    assert_eq!(q[0], 1);
                }

                #[test]
                fn [<remquo_extreme_and_exceptional_inputs_ $kind>]() {
                    let tiny = $kind::from_bits(1);
                    let large = 2.0_f64.powi(120) as $kind;
                    let x = Simd::from_array([large, $kind::MAX, 7.0 * tiny, -9.0 * tiny,
                        -0.0, $kind::INFINITY, $kind::NAN, 1.0]);
                    let y = Simd::from_array([3.0, $kind::MIN_POSITIVE, 2.0 * tiny, 2.0 * tiny,
                        $kind::INFINITY, 1.0, 2.0, 0.0]);
                    let (r, q) = $function(x, y);
                    assert_eq!(q.to_array(), [5, 0, 4, -4, 0, 0, 0, 0]);
                    for (lane, expected) in [1.0, 0.0, -tiny, -tiny, -0.0].into_iter().enumerate() {
                        assert_eq!(r[lane].to_bits(), expected.to_bits());
                    }
                    for lane in 5..8 {
                        assert!(r[lane].is_nan());
                    }
                }
            }
        };
    }

    remquo_tests!(f32, remquo_f32);
    remquo_tests!(f64, remquo_f64);
}
