//! Exact floating remainders using compensated quotient reduction.
// Based on SLEEF src/libm/sleefsimddp.c (xfmod, xremainder), with changes.
// Copyright Naoki Shibata and contributors 2010 - 2025.
// SPDX-License-Identifier: BSL-1.0

/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

use crate::precision::{frexp, scale, Dd};
use core::simd::prelude::*;
use std::simd::StdFloat;

#[inline]
fn reduce<const N: usize, const NEAREST: bool>(x: Simd<f64, N>, y: Simd<f64, N>) -> Simd<f64, N> {
    let ax = x.abs();
    let ay = y.abs();
    let quotient = ax / ay;
    let quick = ax.simd_lt(Simd::splat(f64::MAX * 0.5))
        & ay.is_finite()
        & ay.simd_ge(Simd::splat(f64::MIN_POSITIVE * 2.0))
        & quotient.simd_lt(Simd::splat(1125899906842624.0));
    if quick.all() {
        let mut q = crate::trunc_f64(quotient);
        let product = Dd::product(q, ay);
        // q is the floor or one integer above it. Cancellation makes both
        // subtractions exact, and the residual has no more bits than y.
        let mut r = (ax - product.hi) - product.lo;
        let below = r.simd_lt(Simd::splat(0.0));
        r = below.select(r + ay, r);
        q -= below.select(Simd::splat(1.0), Simd::splat(0.0));
        if NEAREST {
            let half = ay * Simd::splat(0.5);
            let odd = (q.cast::<u64>() & Simd::splat(1)).simd_ne(Simd::splat(0));
            let subtract = r.simd_gt(half) | (r.simd_eq(half) & odd);
            r = subtract.select(r - ay, r);
        }
        return Simd::from_bits(r.to_bits() ^ (x.to_bits() & Simd::splat(1_u64 << 63)));
    }
    let valid = x.is_finite() & y.is_finite() & y.simd_ne(Simd::splat(0.0));
    let ax = valid.select(x.abs(), Simd::splat(1.0));
    let ay = valid.select(y.abs(), Simd::splat(1.0));
    let (mx, mut ex) = frexp(ax);
    let (my, ey) = frexp(ay);
    let divisor_exponent = ey + Simd::splat(if NEAREST { 1 } else { 0 });
    let mut r = Dd::from(mx);
    // Each quotient removes up to 50 exponent bits. Products and residuals
    // retain their low component, including when x/y overflows.
    loop {
        let gap = ex - divisor_exponent;
        let active = gap.simd_gt(Simd::splat(0))
            | (gap.simd_eq(Simd::splat(0))
                & r.add_float(-my).normalize().hi.simd_ge(Simd::splat(0.0)));
        let active = active & r.hi.simd_ne(Simd::splat(0.0));
        if !active.any() {
            break;
        }
        let chunk = gap.simd_clamp(Simd::splat(0), Simd::splat(50));
        let denominator = scale(my, -chunk);
        let q = crate::trunc_f64(r.hi / denominator);
        let mut next = r.sub(Dd::product(q, denominator)).normalize();
        // Floating division can round across an integer quotient boundary.
        next = Dd::select(
            next.hi.simd_lt(Simd::splat(0.0)),
            next.add_float(denominator),
            next,
        );
        next = Dd::select(
            next.add_float(-denominator)
                .normalize()
                .hi
                .simd_ge(Simd::splat(0.0)),
            next.add_float(-denominator),
            next,
        )
        .normalize();
        next = Dd::select(active, next, r);
        let (mantissa, adjustment) = frexp(next.hi);
        let nonzero = active & next.hi.simd_ne(Simd::splat(0.0));
        r = Dd::select(
            nonzero,
            Dd::new(mantissa, scale(next.lo, -adjustment)),
            next,
        );
        ex += nonzero.select(adjustment, Simd::splat(0));
    }
    let mut result = scale(r.value(), ex);
    if NEAREST {
        let gap = ex - ey;
        let a = Dd::new(
            scale(r.hi, gap.simd_clamp(Simd::splat(-1), Simd::splat(1))),
            scale(r.lo, gap.simd_clamp(Simd::splat(-1), Simd::splat(1))),
        );
        let half = my * Simd::splat(0.5);
        let twice = a
            .sub(Dd::product(my, Simd::splat(1.5)))
            .normalize()
            .hi
            .simd_ge(Simd::splat(0.0));
        let once = a.add_float(-half).normalize().hi.simd_gt(Simd::splat(0.0)) & !twice;
        let q = twice.select(
            Simd::splat(2.0),
            once.select(Simd::splat(1.0), Simd::splat(0.0)),
        );
        let adjusted = scale(a.sub(Dd::product(q, my)).value(), ey);
        result = gap.simd_ge(Simd::splat(-1)).select(adjusted, result);
    }
    // Apply the dividend's sign by xor: a nearest remainder may be negative.
    result = Simd::from_bits(result.to_bits() ^ (x.to_bits() & Simd::splat(1_u64 << 63)));
    result = x.simd_eq(Simd::splat(0.0)).select(x, result);
    let exceptional = (y.is_infinite() & x.is_finite()).select(x, Simd::splat(f64::NAN));
    valid.select(result, exceptional)
}

/// Computes x-y*trunc(x/y) exactly for each lane, including overflowing ratios.
#[inline]
pub fn fmod_f64<const N: usize>(x: Simd<f64, N>, y: Simd<f64, N>) -> Simd<f64, N> {
    reduce::<N, false>(x, y)
}

/// Computes the IEEE remainder, choosing the nearest even integer quotient.
#[inline]
pub fn remainder_f64<const N: usize>(x: Simd<f64, N>, y: Simd<f64, N>) -> Simd<f64, N> {
    reduce::<N, true>(x, y)
}

/// Computes x-y*trunc(x/y) exactly for each lane, including overflowing ratios.
#[inline]
pub fn fmod_f32<const N: usize>(x: Simd<f32, N>, y: Simd<f32, N>) -> Simd<f32, N> {
    reduce_f32::<N, false>(x, y)
}

/// Computes the IEEE remainder, choosing the nearest even integer quotient.
#[inline]
pub fn remainder_f32<const N: usize>(x: Simd<f32, N>, y: Simd<f32, N>) -> Simd<f32, N> {
    reduce_f32::<N, true>(x, y)
}

#[inline]
fn reduce_f32<const N: usize, const NEAREST: bool>(
    x: Simd<f32, N>,
    y: Simd<f32, N>,
) -> Simd<f32, N> {
    let ax = x.abs();
    let ay = y.abs();
    let quotient = ax / ay;
    let quick = x.is_finite() & y.is_finite() & quotient.simd_lt(Simd::splat(4194304.0));
    if !quick.all() {
        return reduce::<N, NEAREST>(x.cast(), y.cast()).cast();
    }
    let mut q = crate::trunc_f32(quotient);
    let mut r = if crate::backend::use_hardware_fma_f32::<N>() {
        (-q).mul_add(ay, ax)
    } else {
        // A bounded integer times an f32 significand fits exactly in f64.
        (ax.cast::<f64>() - q.cast::<f64>() * ay.cast::<f64>()).cast::<f32>()
    };
    let below = r.simd_lt(Simd::splat(0.0));
    r = below.select(r + ay, r);
    q -= below.select(Simd::splat(1.0), Simd::splat(0.0));
    if NEAREST {
        // Comparing the two halves avoids underflow for subnormal divisors.
        let complement = ay - r;
        let odd = (q.cast::<u32>() & Simd::splat(1)).simd_ne(Simd::splat(0));
        let subtract = r.simd_gt(complement) | (r.simd_eq(complement) & odd);
        r = subtract.select(r - ay, r);
    }
    Simd::from_bits(r.to_bits() ^ (x.to_bits() & Simd::splat(1_u32 << 31)))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn infinite_divisors_preserve_the_dividend() {
        let x = Simd::from_array([-0.0, 2.0, -3.0, f64::MIN_POSITIVE]);
        let y = Simd::from_array([
            f64::NEG_INFINITY,
            f64::INFINITY,
            f64::NEG_INFINITY,
            f64::INFINITY,
        ]);
        assert_eq!(fmod_f64(x, y).to_bits(), x.to_bits());
        assert_eq!(remainder_f64(x, y).to_bits(), x.to_bits());
    }
    #[test]
    fn rounded_three_halves_is_below_the_exact_boundary() {
        let y = f64::from_bits(0x3ff0000000000003);
        let x = y * 1.5;
        assert_eq!(
            remainder_f64(Simd::<f64, 1>::splat(x), Simd::splat(y))[0],
            x - y
        );
    }

    #[test]
    fn ties_signed_zero_and_extreme_ratios() {
        let x = Simd::from_array([1.0, 3.0, 5.0, 7.0, -4.0, f64::MAX, f64::MAX]);
        let y = Simd::from_array([
            2.0,
            2.0,
            2.0,
            2.0,
            2.0,
            f64::from_bits(3),
            f64::MIN_POSITIVE,
        ]);
        let r = remainder_f64(x, y).to_array();
        assert_eq!(&r[..4], &[1.0, -1.0, 1.0, -1.0]);
        assert_eq!(r[4].to_bits(), (-0.0_f64).to_bits());
        assert_eq!(r[6], 0.0);
        for i in 0..7 {
            assert_eq!(fmod_f64(x, y)[i].to_bits(), (x[i] % y[i]).to_bits());
        }
    }
}
